# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
- repo: https://github.com/posit-dev/air-pre-commit
  rev: 0.8.2
  hooks:
    - id: air-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=200']
    - id: file-contents-sorter
      files: '^\.Rbuildignore$'
    - id: check-yaml
- repo: local
  hooks:
    - id: forbid-to-commit
      name: Don't commit common R artifacts
      entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
      language: fail
      files: '\.Rhistory|\.RData|\.Rds|\.rds$'
