---
title: "Virtual gene panels"
output: rmarkdown::html_document
---

<br>

The cancer predisposition report can show variants found in a number of well-known cancer predisposition genes, and the specific set of genes can be customized by the user by choosing any of the following __virtual gene panels (0 - 42)__:

  * **Panel 0** is a comprehensive, research-based _superpanel_ assembled through known sources on cancer predisposition:
	* A list of 152 genes that were curated and established within TCGA’s pan-cancer study ([Huang et al., *Cell*, 2018](https://www.ncbi.nlm.nih.gov/pubmed/29625052))
	* A list of 107 protein-coding genes that has been manually curated in COSMIC’s [Cancer Gene Census v91](https://cancer.sanger.ac.uk/census),
	* Genes from all [Genomics England PanelApp](https://panelapp.genomicsengland.co.uk/) panels for inherited cancers and tumor syndromes (detailed below)
	* Additional genes deemed relevant for cancer predisposition (contributed by the CPSR user community)


	The combination of the above sources resulted in a [non-redundant set of n = 433
	genes](https://cpsr.readthedocs.io/en/latest/superpanel.html) of relevance for cancer predisposition (see complete details [below](#panel-0))
	
	Data with respect to mechanisms of inheritance (<i>MoI</i> - autosomal recessive (AR) vs. autosomal
	dominant (AD) etc.) and whether mechanisms of disease are associated with loss-of-function (<i>LoF</i>) or
  gain-of-function (<i>GoF</i>) were primarily retrieved from [Maxwell et al., Am J Hum Genet, 2016](https://www.ncbi.nlm.nih.gov/pubmed/27153395), and [Genomics England PanelApp](https://panelapp.genomicsengland.co.uk/). We want to make it explicit that this list is by no means regarded as an international consensus, but should rather be subject to continuous update by the international community that carry expertise on genetic risk factors for cancer. Do you miss other genes of relevance for cancer predisposition/inherited tumor syndromes? Please forward a list of gene identifiers, preferably also with mode of inheritance and literature support to sigven AT ifi.uio.no, so we can include them in Panel 0.

* **Panels 1 - 44** are panels for inherited cancers and tumor syndromes assembled within the [Genomics England PanelApp](https://panelapp.genomicsengland.co.uk/):

| Panel | Description |
|-------|-------------|
| 1  | [Adult solid tumours cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/245/) |
| 2  | [Adult solid tumours for rare disease](https://panelapp.genomicsengland.co.uk/panels/391/) |
| 3  | [Bladder cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/208/) |
| 4  | [Brain cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/166/) |
| 5  | [Breast cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/55/) |
| 6  | [Childhood solid tumours cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/259/) |
| 7  | [Colorectal cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/244/) |
| 8  | [Endometrial cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/271/) |
| 9  | [Familial Tumours Syndromes of the central & peripheral Nervous system](https://panelapp.genomicsengland.co.uk/panels/167/) |
| 10 | [Familial breast cancer](https://panelapp.genomicsengland.co.uk/panels/158/) |
| 11 | [Familial melanoma](https://panelapp.genomicsengland.co.uk/panels/522/) |
| 12 | [Familial prostate cancer](https://panelapp.genomicsengland.co.uk/panels/318/) |
| 13 | [Familial rhabdomyosarcoma](https://panelapp.genomicsengland.co.uk/panels/290/) |
| 14 | [GI tract tumours](https://panelapp.genomicsengland.co.uk/panels/254/) |
| 15 | [Genodermatoses with malignancies](https://panelapp.genomicsengland.co.uk/panels/201/) |
| 16 | [Haematological malignancies cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/59/) |
| 17 | [Haematological malignancies for rare disease](https://panelapp.genomicsengland.co.uk/panels/407/) |
| 18 | [Head and neck cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/115/) |
| 19 | [Inherited MMR deficiency (Lynch syndrome)](https://panelapp.genomicsengland.co.uk/panels/503/) |
| 20 | [Inherited non-medullary thyroid cancer](https://panelapp.genomicsengland.co.uk/panels/171/) |
| 21 | [Inherited ovarian cancer (without breast cancer)](https://panelapp.genomicsengland.co.uk/panels/143/) |
| 22 | [Inherited pancreatic cancer](https://panelapp.genomicsengland.co.uk/panels/524/) |
| 23 | [Inherited polyposis and early onset colorectal cancer](https://panelapp.genomicsengland.co.uk/panels/504/) |
| 24 | [Inherited predisposition to acute myeloid leukaemia (AML)](https://panelapp.genomicsengland.co.uk/panels/525/) |
| 25 | [Inherited susceptibility to acute lymphoblastoid leukaemia (ALL)](https://panelapp.genomicsengland.co.uk/panels/1349/) |
| 26 | [Inherited predisposition to GIST](https://panelapp.genomicsengland.co.uk/panels/523/) |
| 27 | [Inherited renal cancer](https://panelapp.genomicsengland.co.uk/panels/521/) |
| 28 | [Inherited phaeochromocytoma and paraganglioma](https://panelapp.genomicsengland.co.uk/panels/97/) |
| 29 | [Melanoma pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/133/) |
| 30 | [Multiple endocrine tumours](https://panelapp.genomicsengland.co.uk/panels/36/) |
| 31 | [Multiple monogenic benign skin tumours](https://panelapp.genomicsengland.co.uk/panels/558/) |
| 32 | [Neuroendocrine cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/183/) |
| 33 | [Neurofibromatosis Type 1](https://panelapp.genomicsengland.co.uk/panels/255/) |
| 34 | [Ovarian cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/117/) |
| 35 | [Parathyroid Cancer](https://panelapp.genomicsengland.co.uk/panels/86/) |
| 36 | [Prostate cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/17/) |
| 37 | [Renal cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/154/) |
| 38 | [Rhabdoid tumour predisposition](https://panelapp.genomicsengland.co.uk/panels/600/) |
| 39 | [Sarcoma cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/217/) |
| 40 | [Sarcoma susceptibility](https://panelapp.genomicsengland.co.uk/panels/734/) |
| 41 | [Thyroid cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/421/) |
| 42 | [Childhood solid tumours](https://panelapp.genomicsengland.co.uk/panels/243/) |
| 43 | [Upper gastrointestinal cancer pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/273/) |
| 44 | [DNA repair genes pertinent cancer susceptibility](https://panelapp.genomicsengland.co.uk/panels/256/) |


## Panel 0

[Download the complete set of CPSR superpanel genes, grch37/grch38 versions (xlsx)](https://sigven.github.io/cpsr/cpsr_superpanel_2022_01.xlsx)


|  no | gene_link                                                                          | entrezgene | ensembl_gene_id | moi       | mod | gene_name                                                                                         | source                                           | phenotype_syndrome_term                                                                                                                      |
|----:|:-----------------------------------------------------------------------------------|-----------:|:----------------|:----------|:----|:--------------------------------------------------------------------------------------------------|:-------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------|
|   1 | <a href='https://www.ncbi.nlm.nih.gov/gene/8647' target='_blank'>ABCB11</a>        |       8647 | ENSG00000073734 | AR        | LoF | ATP binding cassette subfamily B member 11                                                        | TCGA_PANCAN_2018                                 | Crigler-Najjar syndrome, type II                                                                                                             |
|   2 | <a href='https://www.ncbi.nlm.nih.gov/gene/25' target='_blank'>ABL1</a>            |         25 | ENSG00000097007 | NA        | NA  | ABL proto-oncogene 1, non-receptor tyrosine kinase                                                | OTHER                                            | NA                                                                                                                                           |
|   3 | <a href='https://www.ncbi.nlm.nih.gov/gene/27' target='_blank'>ABL2</a>            |         27 | ENSG00000143322 | NA        | NA  | ABL proto-oncogene 2, non-receptor tyrosine kinase                                                | OTHER                                            | NA                                                                                                                                           |
|   4 | <a href='https://www.ncbi.nlm.nih.gov/gene/84142' target='_blank'>ABRAXAS1</a>     |      84142 | ENSG00000163322 | NA        | NA  | abraxas 1, BRCA1 A complex subunit                                                                | NCGC                                             | NA                                                                                                                                           |
|   5 | <a href='https://www.ncbi.nlm.nih.gov/gene/65057' target='_blank'>ACD</a>          |      65057 | ENSG00000102977 | AD/AR     | NA  | ACD shelterin complex subunit and telomerase recruitment factor                                   | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|   6 | <a href='https://www.ncbi.nlm.nih.gov/gene/139741' target='_blank'>ACTRT1</a>      |     139741 | ENSG00000123165 | AD        | NA  | actin related protein T1                                                                          | PANEL_APP                                        | NA                                                                                                                                           |
|   7 | <a href='https://www.ncbi.nlm.nih.gov/gene/133' target='_blank'>ADM</a>            |        133 | ENSG00000148926 | NA        | NA  | adrenomedullin                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
|   8 | <a href='https://www.ncbi.nlm.nih.gov/gene/9049' target='_blank'>AIP</a>           |       9049 | ENSG00000110711 | AD        | LoF | aryl hydrocarbon receptor interacting protein                                                     | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|   9 | <a href='https://www.ncbi.nlm.nih.gov/gene/207' target='_blank'>AKT1</a>           |        207 | ENSG00000142208 | AD        | GoF | AKT serine/threonine kinase 1                                                                     | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|  10 | <a href='https://www.ncbi.nlm.nih.gov/gene/238' target='_blank'>ALK</a>            |        238 | ENSG00000171094 | AD        | GoF | ALK receptor tyrosine kinase                                                                      | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Neuroblastoma                                                                                                                                |
|  11 | <a href='https://www.ncbi.nlm.nih.gov/gene/139285' target='_blank'>AMER1</a>       |     139285 | ENSG00000184675 | NA        | NA  | APC membrane recruitment protein 1                                                                | OTHER                                            | NA                                                                                                                                           |
|  12 | <a href='https://www.ncbi.nlm.nih.gov/gene/22852' target='_blank'>ANKRD26</a>      |      22852 | ENSG00000107890 | AD        | NA  | ankyrin repeat domain 26                                                                          | PANEL_APP                                        | NA                                                                                                                                           |
|  13 | <a href='https://www.ncbi.nlm.nih.gov/gene/324' target='_blank'>APC</a>            |        324 | ENSG00000134982 | AD/AR     | LoF | APC regulator of WNT signaling pathway                                                            | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Familial multiple polyposis syndrome; Familial adenomatous polyposis 1                                                                       |
|  14 | <a href='https://www.ncbi.nlm.nih.gov/gene/9582' target='_blank'>APOBEC3B</a>      |       9582 | ENSG00000179750 | AR        | NA  | apolipoprotein B mRNA editing enzyme catalytic subunit 3B                                         | CGC_94                                           | NA                                                                                                                                           |
|  15 | <a href='https://www.ncbi.nlm.nih.gov/gene/367' target='_blank'>AR</a>             |        367 | ENSG00000169083 | AD        | NA  | androgen receptor                                                                                 | CGC_94,PANEL_APP                                 | NA                                                                                                                                           |
|  16 | <a href='https://www.ncbi.nlm.nih.gov/gene/23365' target='_blank'>ARHGEF12</a>     |      23365 | ENSG00000196914 | NA        | NA  | Rho guanine nucleotide exchange factor 12                                                         | OTHER                                            | NA                                                                                                                                           |
|  17 | <a href='https://www.ncbi.nlm.nih.gov/gene/8289' target='_blank'>ARID1A</a>        |       8289 | ENSG00000117713 | AD        | NA  | AT-rich interaction domain 1A                                                                     | OTHER                                            | NA                                                                                                                                           |
|  18 | <a href='https://www.ncbi.nlm.nih.gov/gene/196528' target='_blank'>ARID2</a>       |     196528 | ENSG00000189079 | AD        | NA  | AT-rich interaction domain 2                                                                      | OTHER                                            | NA                                                                                                                                           |
|  19 | <a href='https://www.ncbi.nlm.nih.gov/gene/84159' target='_blank'>ARID5B</a>       |      84159 | ENSG00000150347 | NA        | NA  | AT-rich interaction domain 5B                                                                     | OTHER                                            | NA                                                                                                                                           |
|  20 | <a href='https://www.ncbi.nlm.nih.gov/gene/79798' target='_blank'>ARMC5</a>        |      79798 | ENSG00000140691 | AD        | NA  | armadillo repeat containing 5                                                                     | OTHER                                            | NA                                                                                                                                           |
|  21 | <a href='https://www.ncbi.nlm.nih.gov/gene/171023' target='_blank'>ASXL1</a>       |     171023 | ENSG00000171456 | NA        | NA  | ASXL transcriptional regulator 1                                                                  | OTHER                                            | NA                                                                                                                                           |
|  22 | <a href='https://www.ncbi.nlm.nih.gov/gene/472' target='_blank'>ATM</a>            |        472 | ENSG00000149311 | AD/AR     | LoF | ATM serine/threonine kinase                                                                       | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Ataxia-telangiectasia syndrome                                                                                                               |
|  23 | <a href='https://www.ncbi.nlm.nih.gov/gene/545' target='_blank'>ATR</a>            |        545 | ENSG00000175054 | AD        | LoF | ATR serine/threonine kinase                                                                       | CGC_94,PANEL_APP,TCGA_PANCAN_2018                | Seckel syndrome; Cutaneous telangiectasia and cancer syndrome, familial                                                                      |
|  24 | <a href='https://www.ncbi.nlm.nih.gov/gene/546' target='_blank'>ATRX</a>           |        546 | ENSG00000085224 | NA        | NA  | ATRX chromatin remodeler                                                                          | OTHER                                            | NA                                                                                                                                           |
|  25 | <a href='https://www.ncbi.nlm.nih.gov/gene/8312' target='_blank'>AXIN1</a>         |       8312 | ENSG00000103126 | NA        | NA  | axin 1                                                                                            | NCGC                                             | NA                                                                                                                                           |
|  26 | <a href='https://www.ncbi.nlm.nih.gov/gene/8313' target='_blank'>AXIN2</a>         |       8313 | ENSG00000168646 | AD/AR     | LoF | axin 2                                                                                            | CGC_94,NCGC,TCGA_PANCAN_2018                     | Oligodontia-colorectal cancer syndrome                                                                                                       |
|  27 | <a href='https://www.ncbi.nlm.nih.gov/gene/8314' target='_blank'>BAP1</a>          |       8314 | ENSG00000163930 | AD/AR     | LoF | BRCA1 associated protein 1                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Tumor susceptibility linked to germline BAP1 mutations; BAP1 Cancer Syndrome                                                                 |
|  28 | <a href='https://www.ncbi.nlm.nih.gov/gene/580' target='_blank'>BARD1</a>          |        580 | ENSG00000138376 | AR        | LoF | BRCA1 associated RING domain 1                                                                    | CGC_94,NCGC,PANEL_APP                            | NA                                                                                                                                           |
|  29 | <a href='https://www.ncbi.nlm.nih.gov/gene/8915' target='_blank'>BCL10</a>         |       8915 | ENSG00000142867 | AR        | NA  | BCL10 immune signaling adaptor                                                                    | OTHER                                            | NA                                                                                                                                           |
|  30 | <a href='https://www.ncbi.nlm.nih.gov/gene/613' target='_blank'>BCR</a>            |        613 | ENSG00000186716 | NA        | NA  | BCR activator of RhoGEF and GTPase                                                                | OTHER                                            | NA                                                                                                                                           |
|  31 | <a href='https://www.ncbi.nlm.nih.gov/gene/641' target='_blank'>BLM</a>            |        641 | ENSG00000197299 | AR        | LoF | BLM RecQ like helicase                                                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Bloom syndrome                                                                                                                               |
|  32 | <a href='https://www.ncbi.nlm.nih.gov/gene/657' target='_blank'>BMPR1A</a>         |        657 | ENSG00000107779 | AD/AR     | LoF | bone morphogenetic protein receptor type 1A                                                       | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Juvenile polyposis syndrome                                                                                                                  |
|  33 | <a href='https://www.ncbi.nlm.nih.gov/gene/673' target='_blank'>BRAF</a>           |        673 | ENSG00000157764 | AD        | NA  | B-Raf proto-oncogene, serine/threonine kinase                                                     | PANEL_APP,TCGA_PANCAN_2018                       | Noonan syndrome 7; LEOPARD syndrome 3                                                                                                        |
|  34 | <a href='https://www.ncbi.nlm.nih.gov/gene/672' target='_blank'>BRCA1</a>          |        672 | ENSG00000012048 | AD/AR     | LoF | BRCA1 DNA repair associated                                                                       | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary breast and ovarian cancer syndrome                                                                                                |
|  35 | <a href='https://www.ncbi.nlm.nih.gov/gene/675' target='_blank'>BRCA2</a>          |        675 | ENSG00000139618 | AD/AR     | LoF | BRCA2 DNA repair associated                                                                       | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary breast and ovarian cancer syndrome; Fanconi anemia, complementation group D1                                                      |
|  36 | <a href='https://www.ncbi.nlm.nih.gov/gene/83990' target='_blank'>BRIP1</a>        |      83990 | ENSG00000136492 | AD/AR     | LoF | BRCA1 interacting helicase 1                                                                      | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group J                                                                                                      |
|  37 | <a href='https://www.ncbi.nlm.nih.gov/gene/695' target='_blank'>BTK</a>            |        695 | ENSG00000010671 | XLR       | NA  | Bruton tyrosine kinase                                                                            | OTHER                                            | NA                                                                                                                                           |
|  38 | <a href='https://www.ncbi.nlm.nih.gov/gene/699' target='_blank'>BUB1</a>           |        699 | ENSG00000169679 | NA        | NA  | BUB1 mitotic checkpoint serine/threonine kinase                                                   | NCGC                                             | NA                                                                                                                                           |
|  39 | <a href='https://www.ncbi.nlm.nih.gov/gene/701' target='_blank'>BUB1B</a>          |        701 | ENSG00000156970 | AR        | LoF | BUB1 mitotic checkpoint serine/threonine kinase B                                                 | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Mosaic variegated aneuploidy syndrome 1                                                                                                      |
|  40 | <a href='https://www.ncbi.nlm.nih.gov/gene/9184' target='_blank'>BUB3</a>          |       9184 | ENSG00000154473 | NA        | NA  | BUB3 mitotic checkpoint protein                                                                   | OTHER                                            | NA                                                                                                                                           |
|  41 | <a href='https://www.ncbi.nlm.nih.gov/gene/23261' target='_blank'>CAMTA1</a>       |      23261 | ENSG00000171735 | NA        | NA  | calmodulin binding transcription activator 1                                                      | OTHER                                            | NA                                                                                                                                           |
|  42 | <a href='https://www.ncbi.nlm.nih.gov/gene/841' target='_blank'>CASP8</a>          |        841 | ENSG00000064012 | AD        | NA  | caspase 8                                                                                         | OTHER                                            | NA                                                                                                                                           |
|  43 | <a href='https://www.ncbi.nlm.nih.gov/gene/846' target='_blank'>CASR</a>           |        846 | ENSG00000036828 | NA        | NA  | calcium sensing receptor                                                                          | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|  44 | <a href='https://www.ncbi.nlm.nih.gov/gene/863' target='_blank'>CBFA2T3</a>        |        863 | ENSG00000129993 | NA        | NA  | CBFA2/RUNX1 partner transcriptional co-repressor 3                                                | OTHER                                            | NA                                                                                                                                           |
|  45 | <a href='https://www.ncbi.nlm.nih.gov/gene/867' target='_blank'>CBL</a>            |        867 | ENSG00000110395 | AD        | LoF | Cbl proto-oncogene                                                                                | PANEL_APP,TCGA_PANCAN_2018                       | Noonan syndrome                                                                                                                              |
|  46 | <a href='https://www.ncbi.nlm.nih.gov/gene/79577' target='_blank'>CDC73</a>        |      79577 | ENSG00000134371 | AD/AR     | LoF | cell division cycle 73                                                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hyperparathyroidism 2                                                                                                                        |
|  47 | <a href='https://www.ncbi.nlm.nih.gov/gene/999' target='_blank'>CDH1</a>           |        999 | ENSG00000039068 | AD/AR     | LoF | cadherin 1                                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hereditary diffuse gastric cancer                                                                                                            |
|  48 | <a href='https://www.ncbi.nlm.nih.gov/gene/1008' target='_blank'>CDH10</a>         |       1008 | ENSG00000040731 | NA        | NA  | cadherin 10                                                                                       | CGC_94                                           | NA                                                                                                                                           |
|  49 | <a href='https://www.ncbi.nlm.nih.gov/gene/1009' target='_blank'>CDH11</a>         |       1009 | ENSG00000140937 | NA        | NA  | cadherin 11                                                                                       | OTHER                                            | NA                                                                                                                                           |
|  50 | <a href='https://www.ncbi.nlm.nih.gov/gene/1019' target='_blank'>CDK4</a>          |       1019 | ENSG00000135446 | AD        | GoF | cyclin dependent kinase 4                                                                         | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hereditary melanoma; Cutaneous malignant melanoma 3                                                                                          |
|  51 | <a href='https://www.ncbi.nlm.nih.gov/gene/1026' target='_blank'>CDKN1A</a>        |       1026 | ENSG00000124762 | NA        | NA  | cyclin dependent kinase inhibitor 1A                                                              | OTHER                                            | NA                                                                                                                                           |
|  52 | <a href='https://www.ncbi.nlm.nih.gov/gene/1027' target='_blank'>CDKN1B</a>        |       1027 | ENSG00000111276 | AD/AR     | LoF | cyclin dependent kinase inhibitor 1B                                                              | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Multiple endocrine neoplasia, type 4                                                                                                         |
|  53 | <a href='https://www.ncbi.nlm.nih.gov/gene/1028' target='_blank'>CDKN1C</a>        |       1028 | ENSG00000129757 | AD        | LoF | cyclin dependent kinase inhibitor 1C                                                              | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Beckwith-Wiedemann syndrome                                                                                                                  |
|  54 | <a href='https://www.ncbi.nlm.nih.gov/gene/1029' target='_blank'>CDKN2A</a>        |       1029 | ENSG00000147889 | AD/AR     | LoF | cyclin dependent kinase inhibitor 2A                                                              | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hereditary melanoma                                                                                                                          |
|  55 | <a href='https://www.ncbi.nlm.nih.gov/gene/1030' target='_blank'>CDKN2B</a>        |       1030 | ENSG00000147883 | AD        | NA  | cyclin dependent kinase inhibitor 2B                                                              | PANEL_APP                                        | NA                                                                                                                                           |
|  56 | <a href='https://www.ncbi.nlm.nih.gov/gene/1031' target='_blank'>CDKN2C</a>        |       1031 | ENSG00000123080 | NA        | NA  | cyclin dependent kinase inhibitor 2C                                                              | OTHER                                            | NA                                                                                                                                           |
|  57 | <a href='https://www.ncbi.nlm.nih.gov/gene/1050' target='_blank'>CEBPA</a>         |       1050 | ENSG00000245848 | AD        | LoF | CCAAT enhancer binding protein alpha                                                              | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Acute myeloid leukemia                                                                                                                       |
|  58 | <a href='https://www.ncbi.nlm.nih.gov/gene/1053' target='_blank'>CEBPE</a>         |       1053 | ENSG00000092067 | AR        | NA  | CCAAT enhancer binding protein epsilon                                                            | OTHER                                            | NA                                                                                                                                           |
|  59 | <a href='https://www.ncbi.nlm.nih.gov/gene/55835' target='_blank'>CENPJ</a>        |      55835 | ENSG00000151849 | NA        | NA  | centromere protein J                                                                              | OTHER                                            | NA                                                                                                                                           |
|  60 | <a href='https://www.ncbi.nlm.nih.gov/gene/9702' target='_blank'>CEP57</a>         |       9702 | ENSG00000166037 | AR        | LoF | centrosomal protein 57                                                                            | NCGC                                             | NA                                                                                                                                           |
|  61 | <a href='https://www.ncbi.nlm.nih.gov/gene/1111' target='_blank'>CHEK1</a>         |       1111 | ENSG00000149554 | NA        | NA  | checkpoint kinase 1                                                                               | NCGC                                             | NA                                                                                                                                           |
|  62 | <a href='https://www.ncbi.nlm.nih.gov/gene/11200' target='_blank'>CHEK2</a>        |      11200 | ENSG00000183765 | AD/AR     | LoF | checkpoint kinase 2                                                                               | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Familial cancer of breast                                                                                                                    |
|  63 | <a href='https://www.ncbi.nlm.nih.gov/gene/10519' target='_blank'>CIB1</a>         |      10519 | ENSG00000185043 | AR        | NA  | calcium and integrin binding 1                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
|  64 | <a href='https://www.ncbi.nlm.nih.gov/gene/1294' target='_blank'>COL7A1</a>        |       1294 | ENSG00000114270 | AD/AR     | LoF | collagen type VII alpha 1 chain                                                                   | TCGA_PANCAN_2018                                 | Epidermolysis bullosa                                                                                                                        |
|  65 | <a href='https://www.ncbi.nlm.nih.gov/gene/1387' target='_blank'>CREBBP</a>        |       1387 | ENSG00000005339 | AD        | NA  | CREB binding protein                                                                              | PANEL_APP                                        | NA                                                                                                                                           |
|  66 | <a href='https://www.ncbi.nlm.nih.gov/gene/1441' target='_blank'>CSF3R</a>         |       1441 | ENSG00000119535 | AD        | NA  | colony stimulating factor 3 receptor                                                              | PANEL_APP                                        | NA                                                                                                                                           |
|  67 | <a href='https://www.ncbi.nlm.nih.gov/gene/80169' target='_blank'>CTC1</a>         |      80169 | ENSG00000178971 | AR        | NA  | CST telomere replication complex component 1                                                      | PANEL_APP                                        | NA                                                                                                                                           |
|  68 | <a href='https://www.ncbi.nlm.nih.gov/gene/1495' target='_blank'>CTNNA1</a>        |       1495 | ENSG00000044115 | AD        | LoF | catenin alpha 1                                                                                   | NCGC,OTHER                                       | NA                                                                                                                                           |
|  69 | <a href='https://www.ncbi.nlm.nih.gov/gene/1499' target='_blank'>CTNNB1</a>        |       1499 | ENSG00000168036 | AD        | NA  | catenin beta 1                                                                                    | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|  70 | <a href='https://www.ncbi.nlm.nih.gov/gene/9646' target='_blank'>CTR9</a>          |       9646 | ENSG00000198730 | AD        | NA  | CTR9 homolog, Paf1/RNA polymerase II complex component                                            | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
|  71 | <a href='https://www.ncbi.nlm.nih.gov/gene/11330' target='_blank'>CTRC</a>         |      11330 | ENSG00000162438 | NA        | NA  | chymotrypsin C                                                                                    | NCGC                                             | NA                                                                                                                                           |
|  72 | <a href='https://www.ncbi.nlm.nih.gov/gene/7852' target='_blank'>CXCR4</a>         |       7852 | ENSG00000121966 | AD        | NA  | C-X-C motif chemokine receptor 4                                                                  | CGC_94                                           | NA                                                                                                                                           |
|  73 | <a href='https://www.ncbi.nlm.nih.gov/gene/1540' target='_blank'>CYLD</a>          |       1540 | ENSG00000083799 | AD/AR     | LoF | CYLD lysine 63 deubiquitinase                                                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Brooke-Spiegler syndrome                                                                                                                     |
|  74 | <a href='https://www.ncbi.nlm.nih.gov/gene/1643' target='_blank'>DDB2</a>          |       1643 | ENSG00000134574 | AD/AR     | LoF | damage specific DNA binding protein 2                                                             | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, group E                                                                                                               |
|  75 | <a href='https://www.ncbi.nlm.nih.gov/gene/1663' target='_blank'>DDX11</a>         |       1663 | ENSG00000013573 | AR        | NA  | DEAD/H-box helicase 11                                                                            | OTHER                                            | NA                                                                                                                                           |
|  76 | <a href='https://www.ncbi.nlm.nih.gov/gene/51428' target='_blank'>DDX41</a>        |      51428 | ENSG00000183258 | AD        | NA  | DEAD-box helicase 41                                                                              | PANEL_APP                                        | NA                                                                                                                                           |
|  77 | <a href='https://www.ncbi.nlm.nih.gov/gene/54487' target='_blank'>DGCR8</a>        |      54487 | ENSG00000128191 | AD        | NA  | DGCR8 microprocessor complex subunit                                                              | PANEL_APP                                        | NA                                                                                                                                           |
|  78 | <a href='https://www.ncbi.nlm.nih.gov/gene/1717' target='_blank'>DHCR7</a>         |       1717 | ENSG00000172893 | AR        | NA  | 7-dehydrocholesterol reductase                                                                    | OTHER                                            | NA                                                                                                                                           |
|  79 | <a href='https://www.ncbi.nlm.nih.gov/gene/23405' target='_blank'>DICER1</a>       |      23405 | ENSG00000100697 | AD/AR     | LoF | dicer 1, ribonuclease III                                                                         | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Pleuropulmonary blastoma; DICER1-related pleuropulmonary blastoma cancer predisposition syndrome                                             |
|  80 | <a href='https://www.ncbi.nlm.nih.gov/gene/9077' target='_blank'>DIRAS3</a>        |       9077 | ENSG00000162595 | NA        | NA  | DIRAS family GTPase 3                                                                             | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
|  81 | <a href='https://www.ncbi.nlm.nih.gov/gene/22894' target='_blank'>DIS3</a>         |      22894 | ENSG00000083520 | NA        | NA  | DIS3 homolog, exosome endoribonuclease and 3’-5’ exoribonuclease                                  | OTHER                                            | NA                                                                                                                                           |
|  82 | <a href='https://www.ncbi.nlm.nih.gov/gene/115752' target='_blank'>DIS3L</a>       |     115752 | ENSG00000166938 | AR        | NA  | DIS3 like exosome 3’-5’ exoribonuclease                                                           | OTHER                                            | NA                                                                                                                                           |
|  83 | <a href='https://www.ncbi.nlm.nih.gov/gene/129563' target='_blank'>DIS3L2</a>      |     129563 | ENSG00000144535 | AR        | LoF | DIS3 like 3’-5’ exoribonuclease 2                                                                 | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Perlman syndrome                                                                                                                             |
|  84 | <a href='https://www.ncbi.nlm.nih.gov/gene/1736' target='_blank'>DKC1</a>          |       1736 | ENSG00000130826 | NA        | LoF | dyskerin pseudouridine synthase 1                                                                 | PANEL_APP,TCGA_PANCAN_2018                       | Dyskeratosis congenita, X-linked                                                                                                             |
|  85 | <a href='https://www.ncbi.nlm.nih.gov/gene/134218' target='_blank'>DNAJC21</a>     |     134218 | ENSG00000168724 | AR        | NA  | DnaJ heat shock protein family (Hsp40) member C21                                                 | PANEL_APP                                        | NA                                                                                                                                           |
|  86 | <a href='https://www.ncbi.nlm.nih.gov/gene/81704' target='_blank'>DOCK8</a>        |      81704 | ENSG00000107099 | AR        | LoF | dedicator of cytokinesis 8                                                                        | PANEL_APP,TCGA_PANCAN_2018                       | Hyper-Immunoglobulin E Syndrome, Autosomal Recessive                                                                                         |
|  87 | <a href='https://www.ncbi.nlm.nih.gov/gene/29102' target='_blank'>DROSHA</a>       |      29102 | ENSG00000113360 | AD        | NA  | drosha ribonuclease III                                                                           | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
|  88 | <a href='https://www.ncbi.nlm.nih.gov/gene/151636' target='_blank'>DTX3L</a>       |     151636 | ENSG00000163840 | NA        | NA  | deltex E3 ubiquitin ligase 3L                                                                     | NCGC                                             | NA                                                                                                                                           |
|  89 | <a href='https://www.ncbi.nlm.nih.gov/gene/1956' target='_blank'>EGFR</a>          |       1956 | ENSG00000146648 | AD        | GoF | epidermal growth factor receptor                                                                  | CGC_94,NCGC,TCGA_PANCAN_2018                     | NA                                                                                                                                           |
|  90 | <a href='https://www.ncbi.nlm.nih.gov/gene/60528' target='_blank'>ELAC2</a>        |      60528 | ENSG00000006744 | NA        | NA  | elaC ribonuclease Z 2                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
|  91 | <a href='https://www.ncbi.nlm.nih.gov/gene/1991' target='_blank'>ELANE</a>         |       1991 | ENSG00000197561 | AD        | LoF | elastase, neutrophil expressed                                                                    | PANEL_APP,TCGA_PANCAN_2018                       | Neutropenia, severe congenital 1, autosomal dominant                                                                                         |
|  92 | <a href='https://www.ncbi.nlm.nih.gov/gene/8518' target='_blank'>ELP1</a>          |       8518 | ENSG00000070061 | AD        | NA  | elongator acetyltransferase complex subunit 1                                                     | PANEL_APP                                        | NA                                                                                                                                           |
|  93 | <a href='https://www.ncbi.nlm.nih.gov/gene/2022' target='_blank'>ENG</a>           |       2022 | ENSG00000106991 | AD        | NA  | endoglin                                                                                          | ACMG_SF30,NCGC,PANEL_APP                         | Hereditary hemorrhagic telangiectasia                                                                                                        |
|  94 | <a href='https://www.ncbi.nlm.nih.gov/gene/2033' target='_blank'>EP300</a>         |       2033 | ENSG00000100393 | AD        | NA  | E1A binding protein p300                                                                          | OTHER                                            | NA                                                                                                                                           |
|  95 | <a href='https://www.ncbi.nlm.nih.gov/gene/2034' target='_blank'>EPAS1</a>         |       2034 | ENSG00000116016 | NA        | NA  | endothelial PAS domain protein 1                                                                  | OTHER                                            | NA                                                                                                                                           |
|  96 | <a href='https://www.ncbi.nlm.nih.gov/gene/4072' target='_blank'>EPCAM</a>         |       4072 | ENSG00000119888 | AD        | LoF | epithelial cell adhesion molecule                                                                 | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Hereditary nonpolyposis colorectal cancer type 8                                                                                             |
|  97 | <a href='https://www.ncbi.nlm.nih.gov/gene/2064' target='_blank'>ERBB2</a>         |       2064 | ENSG00000141736 | NA        | NA  | erb-b2 receptor tyrosine kinase 2                                                                 | OTHER                                            | NA                                                                                                                                           |
|  98 | <a href='https://www.ncbi.nlm.nih.gov/gene/2066' target='_blank'>ERBB4</a>         |       2066 | ENSG00000178568 | AD        | NA  | erb-b2 receptor tyrosine kinase 4                                                                 | CGC_94                                           | NA                                                                                                                                           |
|  99 | <a href='https://www.ncbi.nlm.nih.gov/gene/2067' target='_blank'>ERCC1</a>         |       2067 | ENSG00000012061 | AR        | NA  | ERCC excision repair 1, endonuclease non-catalytic subunit                                        | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Cerebrooculofacioskeletal syndrome 4                                                                                                         |
| 100 | <a href='https://www.ncbi.nlm.nih.gov/gene/2068' target='_blank'>ERCC2</a>         |       2068 | ENSG00000104884 | AR        | LoF | ERCC excision repair 2, TFIIH core complex helicase subunit                                       | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, group D                                                                                                               |
| 101 | <a href='https://www.ncbi.nlm.nih.gov/gene/2071' target='_blank'>ERCC3</a>         |       2071 | ENSG00000163161 | AR        | LoF | ERCC excision repair 3, TFIIH core complex helicase subunit                                       | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, complementation group b                                                                                               |
| 102 | <a href='https://www.ncbi.nlm.nih.gov/gene/2072' target='_blank'>ERCC4</a>         |       2072 | ENSG00000175595 | AR        | LoF | ERCC excision repair 4, endonuclease catalytic subunit                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, group F; Fanconi anemia, complementation group Q                                                                      |
| 103 | <a href='https://www.ncbi.nlm.nih.gov/gene/2073' target='_blank'>ERCC5</a>         |       2073 | ENSG00000134899 | AR        | LoF | ERCC excision repair 5, endonuclease                                                              | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, group G                                                                                                               |
| 104 | <a href='https://www.ncbi.nlm.nih.gov/gene/2074' target='_blank'>ERCC6</a>         |       2074 | ENSG00000225830 | AD/AR     | NA  | ERCC excision repair 6, chromatin remodeling factor                                               | OTHER                                            | NA                                                                                                                                           |
| 105 | <a href='https://www.ncbi.nlm.nih.gov/gene/2078' target='_blank'>ERG</a>           |       2078 | ENSG00000157554 | NA        | NA  | ETS transcription factor ERG                                                                      | OTHER                                            | NA                                                                                                                                           |
| 106 | <a href='https://www.ncbi.nlm.nih.gov/gene/2099' target='_blank'>ESR1</a>          |       2099 | ENSG00000091831 | NA        | NA  | estrogen receptor 1                                                                               | PANEL_APP                                        | NA                                                                                                                                           |
| 107 | <a href='https://www.ncbi.nlm.nih.gov/gene/2120' target='_blank'>ETV6</a>          |       2120 | ENSG00000139083 | AD        | NA  | ETS variant transcription factor 6                                                                | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Thrombocytopenia 5                                                                                                                           |
| 108 | <a href='https://www.ncbi.nlm.nih.gov/gene/9156' target='_blank'>EXO1</a>          |       9156 | ENSG00000174371 | NA        | NA  | exonuclease 1                                                                                     | OTHER                                            | NA                                                                                                                                           |
| 109 | <a href='https://www.ncbi.nlm.nih.gov/gene/2131' target='_blank'>EXT1</a>          |       2131 | ENSG00000182197 | AD/AR     | LoF | exostosin glycosyltransferase 1                                                                   | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Chondrosarcoma                                                                                                                               |
| 110 | <a href='https://www.ncbi.nlm.nih.gov/gene/2132' target='_blank'>EXT2</a>          |       2132 | ENSG00000151348 | AD/AR     | LoF | exostosin glycosyltransferase 2                                                                   | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Multiple exostoses type 2                                                                                                                    |
| 111 | <a href='https://www.ncbi.nlm.nih.gov/gene/2146' target='_blank'>EZH2</a>          |       2146 | ENSG00000106462 | AD        | LoF | enhancer of zeste 2 polycomb repressive complex 2 subunit                                         | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 112 | <a href='https://www.ncbi.nlm.nih.gov/gene/2184' target='_blank'>FAH</a>           |       2184 | ENSG00000103876 | AR        | LoF | fumarylacetoacetate hydrolase                                                                     | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 113 | <a href='https://www.ncbi.nlm.nih.gov/gene/22909' target='_blank'>FAN1</a>         |      22909 | ENSG00000198690 | NA        | NA  | FANCD2 and FANCI associated nuclease 1                                                            | OTHER                                            | NA                                                                                                                                           |
| 114 | <a href='https://www.ncbi.nlm.nih.gov/gene/2175' target='_blank'>FANCA</a>         |       2175 | ENSG00000187741 | AR        | LoF | FA complementation group A                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group A                                                                                                      |
| 115 | <a href='https://www.ncbi.nlm.nih.gov/gene/2187' target='_blank'>FANCB</a>         |       2187 | ENSG00000181544 | NA        | LoF | FA complementation group B                                                                        | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 116 | <a href='https://www.ncbi.nlm.nih.gov/gene/2176' target='_blank'>FANCC</a>         |       2176 | ENSG00000158169 | AR        | LoF | FA complementation group C                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group C                                                                                                      |
| 117 | <a href='https://www.ncbi.nlm.nih.gov/gene/2177' target='_blank'>FANCD2</a>        |       2177 | ENSG00000144554 | AR        | LoF | FA complementation group D2                                                                       | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group D2                                                                                                     |
| 118 | <a href='https://www.ncbi.nlm.nih.gov/gene/2178' target='_blank'>FANCE</a>         |       2178 | ENSG00000112039 | AR        | LoF | FA complementation group E                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group E                                                                                                      |
| 119 | <a href='https://www.ncbi.nlm.nih.gov/gene/2188' target='_blank'>FANCF</a>         |       2188 | ENSG00000183161 | AR        | LoF | FA complementation group F                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group F                                                                                                      |
| 120 | <a href='https://www.ncbi.nlm.nih.gov/gene/2189' target='_blank'>FANCG</a>         |       2189 | ENSG00000221829 | AR        | LoF | FA complementation group G                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Fanconi anemia, complementation group G                                                                                                      |
| 121 | <a href='https://www.ncbi.nlm.nih.gov/gene/55215' target='_blank'>FANCI</a>        |      55215 | ENSG00000140525 | AR        | LoF | FA complementation group I                                                                        | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Fanconi anemia, complementation group I                                                                                                      |
| 122 | <a href='https://www.ncbi.nlm.nih.gov/gene/55120' target='_blank'>FANCL</a>        |      55120 | ENSG00000115392 | AR        | LoF | FA complementation group L                                                                        | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Fanconi anemia, complementation group L                                                                                                      |
| 123 | <a href='https://www.ncbi.nlm.nih.gov/gene/57697' target='_blank'>FANCM</a>        |      57697 | ENSG00000187790 | AD/AR     | LoF | FA complementation group M                                                                        | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | NA                                                                                                                                           |
| 124 | <a href='https://www.ncbi.nlm.nih.gov/gene/355' target='_blank'>FAS</a>            |        355 | ENSG00000026103 | AD        | LoF | Fas cell surface death receptor                                                                   | PANEL_APP,TCGA_PANCAN_2018                       | Autoimmune lymphoproliferative syndrome                                                                                                      |
| 125 | <a href='https://www.ncbi.nlm.nih.gov/gene/2195' target='_blank'>FAT1</a>          |       2195 | ENSG00000083857 | NA        | NA  | FAT atypical cadherin 1                                                                           | CGC_94                                           | NA                                                                                                                                           |
| 126 | <a href='https://www.ncbi.nlm.nih.gov/gene/55294' target='_blank'>FBXW7</a>        |      55294 | ENSG00000109670 | NA        | NA  | F-box and WD repeat domain containing 7                                                           | OTHER                                            | NA                                                                                                                                           |
| 127 | <a href='https://www.ncbi.nlm.nih.gov/gene/2237' target='_blank'>FEN1</a>          |       2237 | ENSG00000168496 | NA        | NA  | flap structure-specific endonuclease 1                                                            | CGC_94                                           | NA                                                                                                                                           |
| 128 | <a href='https://www.ncbi.nlm.nih.gov/gene/8074' target='_blank'>FGF23</a>         |       8074 | ENSG00000118972 | AD/AR     | NA  | fibroblast growth factor 23                                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 129 | <a href='https://www.ncbi.nlm.nih.gov/gene/2260' target='_blank'>FGFR1</a>         |       2260 | ENSG00000077782 | AD        | NA  | fibroblast growth factor receptor 1                                                               | OTHER                                            | NA                                                                                                                                           |
| 130 | <a href='https://www.ncbi.nlm.nih.gov/gene/2263' target='_blank'>FGFR2</a>         |       2263 | ENSG00000066468 | AD        | NA  | fibroblast growth factor receptor 2                                                               | PANEL_APP                                        | NA                                                                                                                                           |
| 131 | <a href='https://www.ncbi.nlm.nih.gov/gene/2261' target='_blank'>FGFR3</a>         |       2261 | ENSG00000068078 | AD        | NA  | fibroblast growth factor receptor 3                                                               | PANEL_APP                                        | NA                                                                                                                                           |
| 132 | <a href='https://www.ncbi.nlm.nih.gov/gene/2271' target='_blank'>FH</a>            |       2271 | ENSG00000091483 | AD/AR     | LoF | fumarate hydratase                                                                                | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hereditary leiomyomatosis and renal cell cancer                                                                                              |
| 133 | <a href='https://www.ncbi.nlm.nih.gov/gene/2272' target='_blank'>FHIT</a>          |       2272 | ENSG00000189283 | NA        | NA  | fragile histidine triad diadenosine triphosphatase                                                | OTHER                                            | NA                                                                                                                                           |
| 134 | <a href='https://www.ncbi.nlm.nih.gov/gene/201163' target='_blank'>FLCN</a>        |     201163 | ENSG00000154803 | AD/AR     | LoF | folliculin                                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | NA                                                                                                                                           |
| 135 | <a href='https://www.ncbi.nlm.nih.gov/gene/2322' target='_blank'>FLT3</a>          |       2322 | ENSG00000122025 | NA        | NA  | fms related receptor tyrosine kinase 3                                                            | OTHER                                            | NA                                                                                                                                           |
| 136 | <a href='https://www.ncbi.nlm.nih.gov/gene/2332' target='_blank'>FMR1</a>          |       2332 | ENSG00000102081 | XD        | NA  | FMRP translational regulator 1                                                                    | OTHER                                            | NA                                                                                                                                           |
| 137 | <a href='https://www.ncbi.nlm.nih.gov/gene/2304' target='_blank'>FOXE1</a>         |       2304 | ENSG00000178919 | AD        | NA  | forkhead box E1                                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 138 | <a href='https://www.ncbi.nlm.nih.gov/gene/2308' target='_blank'>FOXO1</a>         |       2308 | ENSG00000150907 | NA        | NA  | forkhead box O1                                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 139 | <a href='https://www.ncbi.nlm.nih.gov/gene/2309' target='_blank'>FOXO3</a>         |       2309 | ENSG00000118689 | AD        | NA  | forkhead box O3                                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 140 | <a href='https://www.ncbi.nlm.nih.gov/gene/4303' target='_blank'>FOXO4</a>         |       4303 | ENSG00000184481 | NA        | NA  | forkhead box O4                                                                                   | OTHER                                            | NA                                                                                                                                           |
| 141 | <a href='https://www.ncbi.nlm.nih.gov/gene/27086' target='_blank'>FOXP1</a>        |      27086 | ENSG00000114861 | NA        | NA  | forkhead box P1                                                                                   | OTHER                                            | NA                                                                                                                                           |
| 142 | <a href='https://www.ncbi.nlm.nih.gov/gene/2538' target='_blank'>G6PC1</a>         |       2538 | ENSG00000131482 | NA        | NA  | glucose-6-phosphatase catalytic subunit 1                                                         | OTHER                                            | NA                                                                                                                                           |
| 143 | <a href='https://www.ncbi.nlm.nih.gov/gene/79695' target='_blank'>GALNT12</a>      |      79695 | ENSG00000119514 | AD        | LoF | polypeptide N-acetylgalactosaminyltransferase 12                                                  | NCGC                                             | NA                                                                                                                                           |
| 144 | <a href='https://www.ncbi.nlm.nih.gov/gene/2591' target='_blank'>GALNT3</a>        |       2591 | ENSG00000115339 | AR        | NA  | polypeptide N-acetylgalactosaminyltransferase 3                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 145 | <a href='https://www.ncbi.nlm.nih.gov/gene/2623' target='_blank'>GATA1</a>         |       2623 | ENSG00000102145 | NA        | NA  | GATA binding protein 1                                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 146 | <a href='https://www.ncbi.nlm.nih.gov/gene/2624' target='_blank'>GATA2</a>         |       2624 | ENSG00000179348 | AD        | LoF | GATA binding protein 2                                                                            | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Dendritic cell, monocyte, B lymphocyte, and natural killer lymphocyte deficiency                                                             |
| 147 | <a href='https://www.ncbi.nlm.nih.gov/gene/2625' target='_blank'>GATA3</a>         |       2625 | ENSG00000107485 | NA        | NA  | GATA binding protein 3                                                                            | OTHER                                            | NA                                                                                                                                           |
| 148 | <a href='https://www.ncbi.nlm.nih.gov/gene/2629' target='_blank'>GBA</a>           |       2629 | ENSG00000177628 | AR        | LoF | glucosylceramidase beta                                                                           | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 149 | <a href='https://www.ncbi.nlm.nih.gov/gene/2668' target='_blank'>GDNF</a>          |       2668 | ENSG00000168621 | NA        | NA  | glial cell derived neurotrophic factor                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 150 | <a href='https://www.ncbi.nlm.nih.gov/gene/2706' target='_blank'>GJB2</a>          |       2706 | ENSG00000165474 | AD        | LoF | gap junction protein beta 2                                                                       | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 151 | <a href='https://www.ncbi.nlm.nih.gov/gene/2717' target='_blank'>GLA</a>           |       2717 | ENSG00000102393 | NA        | LoF | galactosidase alpha                                                                               | ACMG_SF30,PANEL_APP                              | Fabry disease                                                                                                                                |
| 152 | <a href='https://www.ncbi.nlm.nih.gov/gene/2737' target='_blank'>GLI3</a>          |       2737 | ENSG00000106571 | AD        | NA  | GLI family zinc finger 3                                                                          | OTHER                                            | NA                                                                                                                                           |
| 153 | <a href='https://www.ncbi.nlm.nih.gov/gene/2778' target='_blank'>GNAS</a>          |       2778 | ENSG00000087460 | AD&mosaic | NA  | GNAS complex locus                                                                                | OTHER,PANEL_APP                                  | NA                                                                                                                                           |
| 154 | <a href='https://www.ncbi.nlm.nih.gov/gene/2719' target='_blank'>GPC3</a>          |       2719 | ENSG00000147257 | NA        | LoF | glypican 3                                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Simpson-Golabi-Behmel syndrome type 1                                                                                                        |
| 155 | <a href='https://www.ncbi.nlm.nih.gov/gene/2239' target='_blank'>GPC4</a>          |       2239 | ENSG00000076716 | NA        | NA  | glypican 4                                                                                        | OTHER                                            | NA                                                                                                                                           |
| 156 | <a href='https://www.ncbi.nlm.nih.gov/gene/23432' target='_blank'>GPR161</a>       |      23432 | ENSG00000143147 | AD        | NA  | G protein-coupled receptor 161                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 157 | <a href='https://www.ncbi.nlm.nih.gov/gene/26585' target='_blank'>GREM1</a>        |      26585 | ENSG00000166923 | AD        | GoF | gremlin 1, DAN family BMP antagonist                                                              | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 158 | <a href='https://www.ncbi.nlm.nih.gov/gene/283120' target='_blank'>H19</a>         |     283120 | ENSG00000130600 | NA        | NA  | H19 imprinted maternally expressed transcript                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 159 | <a href='https://www.ncbi.nlm.nih.gov/gene/3026' target='_blank'>HABP2</a>         |       3026 | ENSG00000148702 | AD        | NA  | hyaluronan binding protein 2                                                                      | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 160 | <a href='https://www.ncbi.nlm.nih.gov/gene/10456' target='_blank'>HAX1</a>         |      10456 | ENSG00000143575 | AR        | NA  | HCLS1 associated protein X-1                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 161 | <a href='https://www.ncbi.nlm.nih.gov/gene/3077' target='_blank'>HFE</a>           |       3077 | ENSG00000010704 | AR        | LoF | homeostatic iron regulator                                                                        | ACMG_SF30,TCGA_PANCAN_2018                       | Hereditary hemochromatosis                                                                                                                   |
| 162 | <a href='https://www.ncbi.nlm.nih.gov/gene/3145' target='_blank'>HMBS</a>          |       3145 | ENSG00000256269 | AD        | LoF | hydroxymethylbilane synthase                                                                      | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 163 | <a href='https://www.ncbi.nlm.nih.gov/gene/6927' target='_blank'>HNF1A</a>         |       6927 | ENSG00000135100 | AR        | LoF | HNF1 homeobox A                                                                                   | ACMG_SF30,CGC_94,NCGC,TCGA_PANCAN_2018           | Hepatic adenomas, familial; NA                                                                                                               |
| 164 | <a href='https://www.ncbi.nlm.nih.gov/gene/6928' target='_blank'>HNF1B</a>         |       6928 | ENSG00000275410 | NA        | NA  | HNF1 homeobox B                                                                                   | NCGC                                             | NA                                                                                                                                           |
| 165 | <a href='https://www.ncbi.nlm.nih.gov/gene/10481' target='_blank'>HOXB13</a>       |      10481 | ENSG00000159184 | AD        | NA  | homeobox B13                                                                                      | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 166 | <a href='https://www.ncbi.nlm.nih.gov/gene/3265' target='_blank'>HRAS</a>          |       3265 | ENSG00000174775 | AD        | GoF | HRas proto-oncogene, GTPase                                                                       | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Costello syndrome                                                                                                                            |
| 167 | <a href='https://www.ncbi.nlm.nih.gov/gene/3417' target='_blank'>IDH1</a>          |       3417 | ENSG00000138413 | NA        | NA  | isocitrate dehydrogenase (NADP(+)) 1                                                              | OTHER                                            | NA                                                                                                                                           |
| 168 | <a href='https://www.ncbi.nlm.nih.gov/gene/3481' target='_blank'>IGF2</a>          |       3481 | ENSG00000167244 | NA        | NA  | insulin like growth factor 2                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 169 | <a href='https://www.ncbi.nlm.nih.gov/gene/3482' target='_blank'>IGF2R</a>         |       3482 | ENSG00000197081 | NA        | NA  | insulin like growth factor 2 receptor                                                             | OTHER                                            | NA                                                                                                                                           |
| 170 | <a href='https://www.ncbi.nlm.nih.gov/gene/10320' target='_blank'>IKZF1</a>        |      10320 | ENSG00000185811 | AD        | NA  | IKAROS family zinc finger 1                                                                       | OTHER,PANEL_APP                                  | NA                                                                                                                                           |
| 171 | <a href='https://www.ncbi.nlm.nih.gov/gene/22806' target='_blank'>IKZF3</a>        |      22806 | ENSG00000161405 | NA        | NA  | IKAROS family zinc finger 3                                                                       | OTHER                                            | NA                                                                                                                                           |
| 172 | <a href='https://www.ncbi.nlm.nih.gov/gene/3662' target='_blank'>IRF4</a>          |       3662 | ENSG00000137265 | AD        | NA  | interferon regulatory factor 4                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 173 | <a href='https://www.ncbi.nlm.nih.gov/gene/3702' target='_blank'>ITK</a>           |       3702 | ENSG00000113263 | AR        | LoF | IL2 inducible T cell kinase                                                                       | PANEL_APP,TCGA_PANCAN_2018                       | Lymphoproliferative syndrome 1                                                                                                               |
| 174 | <a href='https://www.ncbi.nlm.nih.gov/gene/3716' target='_blank'>JAK1</a>          |       3716 | ENSG00000162434 | NA        | NA  | Janus kinase 1                                                                                    | OTHER                                            | NA                                                                                                                                           |
| 175 | <a href='https://www.ncbi.nlm.nih.gov/gene/3717' target='_blank'>JAK2</a>          |       3717 | ENSG00000096968 | AD/AR     | NA  | Janus kinase 2                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 176 | <a href='https://www.ncbi.nlm.nih.gov/gene/3718' target='_blank'>JAK3</a>          |       3718 | ENSG00000105639 | AR        | NA  | Janus kinase 3                                                                                    | OTHER                                            | NA                                                                                                                                           |
| 177 | <a href='https://www.ncbi.nlm.nih.gov/gene/221037' target='_blank'>JMJD1C</a>      |     221037 | ENSG00000171988 | AD        | NA  | jumonji domain containing 1C                                                                      | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 178 | <a href='https://www.ncbi.nlm.nih.gov/gene/3784' target='_blank'>KCNQ1</a>         |       3784 | ENSG00000053918 | AD        | LoF | potassium voltage-gated channel subfamily Q member 1                                              | ACMG_SF30,OTHER                                  | Long QT syndrome 1                                                                                                                           |
| 179 | <a href='https://www.ncbi.nlm.nih.gov/gene/10984' target='_blank'>KCNQ1OT1</a>     |      10984 | ENSG00000269821 | NA        | NA  | KCNQ1 opposite strand/antisense transcript 1                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 180 | <a href='https://www.ncbi.nlm.nih.gov/gene/51780' target='_blank'>KDM3B</a>        |      51780 | ENSG00000120733 | NA        | NA  | lysine demethylase 3B                                                                             | OTHER                                            | NA                                                                                                                                           |
| 181 | <a href='https://www.ncbi.nlm.nih.gov/gene/3791' target='_blank'>KDR</a>           |       3791 | ENSG00000128052 | AD        | NA  | kinase insert domain receptor                                                                     | CGC_94                                           | NA                                                                                                                                           |
| 182 | <a href='https://www.ncbi.nlm.nih.gov/gene/23095' target='_blank'>KIF1B</a>        |      23095 | ENSG00000054523 | NA        | NA  | kinesin family member 1B                                                                          | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 183 | <a href='https://www.ncbi.nlm.nih.gov/gene/84634' target='_blank'>KISS1R</a>       |      84634 | ENSG00000116014 | NA        | NA  | KISS1 receptor                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 184 | <a href='https://www.ncbi.nlm.nih.gov/gene/3815' target='_blank'>KIT</a>           |       3815 | ENSG00000157404 | AD        | GoF | KIT proto-oncogene, receptor tyrosine kinase                                                      | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Gastrointestinal stromal tumor                                                                                                               |
| 185 | <a href='https://www.ncbi.nlm.nih.gov/gene/4254' target='_blank'>KITLG</a>         |       4254 | ENSG00000049130 | AD        | NA  | KIT ligand                                                                                        | PANEL_APP                                        | NA                                                                                                                                           |
| 186 | <a href='https://www.ncbi.nlm.nih.gov/gene/1316' target='_blank'>KLF6</a>          |       1316 | ENSG00000067082 | NA        | NA  | Kruppel like factor 6                                                                             | OTHER                                            | NA                                                                                                                                           |
| 187 | <a href='https://www.ncbi.nlm.nih.gov/gene/100144748' target='_blank'>KLLN</a>     |  100144748 | ENSG00000227268 | NA        | NA  | killin, p53 regulated DNA replication inhibitor                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 188 | <a href='https://www.ncbi.nlm.nih.gov/gene/8085' target='_blank'>KMT2D</a>         |       8085 | ENSG00000167548 | NA        | NA  | lysine methyltransferase 2D                                                                       | OTHER                                            | NA                                                                                                                                           |
| 189 | <a href='https://www.ncbi.nlm.nih.gov/gene/3845' target='_blank'>KRAS</a>          |       3845 | ENSG00000133703 | AD/AR     | NA  | KRAS proto-oncogene, GTPase                                                                       | PANEL_APP,TCGA_PANCAN_2018                       | Noonan syndrome 3; RAS-associated autoimmune leukoproliferative disorder                                                                     |
| 190 | <a href='https://www.ncbi.nlm.nih.gov/gene/3872' target='_blank'>KRT17</a>         |       3872 | ENSG00000128422 | AD        | NA  | keratin 17                                                                                        | PANEL_APP                                        | NA                                                                                                                                           |
| 191 | <a href='https://www.ncbi.nlm.nih.gov/gene/79944' target='_blank'>L2HGDH</a>       |      79944 | ENSG00000087299 | AR        | NA  | L-2-hydroxyglutarate dehydrogenase                                                                | OTHER                                            | NA                                                                                                                                           |
| 192 | <a href='https://www.ncbi.nlm.nih.gov/gene/3932' target='_blank'>LCK</a>           |       3932 | ENSG00000182866 | AR        | NA  | LCK proto-oncogene, Src family tyrosine kinase                                                    | OTHER                                            | NA                                                                                                                                           |
| 193 | <a href='https://www.ncbi.nlm.nih.gov/gene/51176' target='_blank'>LEF1</a>         |      51176 | ENSG00000138795 | AD        | NA  | lymphoid enhancer binding factor 1                                                                | PANEL_APP                                        | NA                                                                                                                                           |
| 194 | <a href='https://www.ncbi.nlm.nih.gov/gene/23592' target='_blank'>LEMD3</a>        |      23592 | ENSG00000174106 | AD        | NA  | LEM domain containing 3                                                                           | PANEL_APP                                        | NA                                                                                                                                           |
| 195 | <a href='https://www.ncbi.nlm.nih.gov/gene/3981' target='_blank'>LIG4</a>          |       3981 | ENSG00000174405 | AR        | NA  | DNA ligase 4                                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 196 | <a href='https://www.ncbi.nlm.nih.gov/gene/4004' target='_blank'>LMO1</a>          |       4004 | ENSG00000166407 | AD        | NA  | LIM domain only 1                                                                                 | CGC_94,TCGA_PANCAN_2018                          | Neuroblastoma, susceptibility to, 7                                                                                                          |
| 197 | <a href='https://www.ncbi.nlm.nih.gov/gene/121227' target='_blank'>LRIG3</a>       |     121227 | ENSG00000139263 | NA        | NA  | leucine rich repeats and immunoglobulin like domains 3                                            | OTHER                                            | NA                                                                                                                                           |
| 198 | <a href='https://www.ncbi.nlm.nih.gov/gene/8216' target='_blank'>LZTR1</a>         |       8216 | ENSG00000099949 | AD/AR     | NA  | leucine zipper like transcription regulator 1                                                     | CGC_94,NCGC,PANEL_APP                            | NA                                                                                                                                           |
| 199 | <a href='https://www.ncbi.nlm.nih.gov/gene/10459' target='_blank'>MAD2L2</a>       |      10459 | ENSG00000116670 | AR        | NA  | mitotic arrest deficient 2 like 2                                                                 | PANEL_APP                                        | NA                                                                                                                                           |
| 200 | <a href='https://www.ncbi.nlm.nih.gov/gene/4094' target='_blank'>MAF</a>           |       4094 | ENSG00000178573 | NA        | NA  | MAF bZIP transcription factor                                                                     | OTHER                                            | NA                                                                                                                                           |
| 201 | <a href='https://www.ncbi.nlm.nih.gov/gene/9935' target='_blank'>MAFB</a>          |       9935 | ENSG00000204103 | NA        | NA  | MAF bZIP transcription factor B                                                                   | OTHER                                            | NA                                                                                                                                           |
| 202 | <a href='https://www.ncbi.nlm.nih.gov/gene/5604' target='_blank'>MAP2K1</a>        |       5604 | ENSG00000169032 | AD        | NA  | mitogen-activated protein kinase kinase 1                                                         | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 203 | <a href='https://www.ncbi.nlm.nih.gov/gene/5605' target='_blank'>MAP2K2</a>        |       5605 | ENSG00000126934 | AD        | NA  | mitogen-activated protein kinase kinase 2                                                         | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 204 | <a href='https://www.ncbi.nlm.nih.gov/gene/6416' target='_blank'>MAP2K4</a>        |       6416 | ENSG00000065559 | NA        | NA  | mitogen-activated protein kinase kinase 4                                                         | OTHER                                            | NA                                                                                                                                           |
| 205 | <a href='https://www.ncbi.nlm.nih.gov/gene/4214' target='_blank'>MAP3K1</a>        |       4214 | ENSG00000095015 | NA        | NA  | mitogen-activated protein kinase kinase kinase 1                                                  | NCGC                                             | NA                                                                                                                                           |
| 206 | <a href='https://www.ncbi.nlm.nih.gov/gene/4149' target='_blank'>MAX</a>           |       4149 | ENSG00000125952 | AD/AR     | LoF | MYC associated factor X                                                                           | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary Paraganglioma-Pheochromocytoma Syndromes                                                                                          |
| 207 | <a href='https://www.ncbi.nlm.nih.gov/gene/8930' target='_blank'>MBD4</a>          |       8930 | ENSG00000129071 | AR        | NA  | methyl-CpG binding domain 4, DNA glycosylase                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 208 | <a href='https://www.ncbi.nlm.nih.gov/gene/4157' target='_blank'>MC1R</a>          |       4157 | ENSG00000258839 | AR        | NA  | melanocortin 1 receptor                                                                           | PANEL_APP                                        | NA                                                                                                                                           |
| 209 | <a href='https://www.ncbi.nlm.nih.gov/gene/4191' target='_blank'>MDH2</a>          |       4191 | ENSG00000146701 | AD        | NA  | malate dehydrogenase 2                                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 210 | <a href='https://www.ncbi.nlm.nih.gov/gene/4221' target='_blank'>MEN1</a>          |       4221 | ENSG00000133895 | AD/AR     | LoF | menin 1                                                                                           | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Multiple endocrine neoplasia, type 1                                                                                                         |
| 211 | <a href='https://www.ncbi.nlm.nih.gov/gene/4233' target='_blank'>MET</a>           |       4233 | ENSG00000105976 | AD        | GoF | MET proto-oncogene, receptor tyrosine kinase                                                      | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Renal cell carcinoma                                                                                                                         |
| 212 | <a href='https://www.ncbi.nlm.nih.gov/gene/9562' target='_blank'>MINPP1</a>        |       9562 | ENSG00000107789 | AD        | NA  | multiple inositol-polyphosphate phosphatase 1                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 213 | <a href='https://www.ncbi.nlm.nih.gov/gene/4286' target='_blank'>MITF</a>          |       4286 | ENSG00000187098 | AD        | GoF | melanocyte inducing transcription factor                                                          | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Hereditary melanoma                                                                                                                          |
| 214 | <a href='https://www.ncbi.nlm.nih.gov/gene/4292' target='_blank'>MLH1</a>          |       4292 | ENSG00000076242 | AD/AR     | LoF | mutL homolog 1                                                                                    | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary nonpolyposis colorectal neoplasms; Turcot syndrome; Hereditary nonpolyposis colon cancer; Lynch syndrome                          |
| 215 | <a href='https://www.ncbi.nlm.nih.gov/gene/27030' target='_blank'>MLH3</a>         |      27030 | ENSG00000119684 | NA        | NA  | mutL homolog 3                                                                                    | NCGC                                             | NA                                                                                                                                           |
| 216 | <a href='https://www.ncbi.nlm.nih.gov/gene/4330' target='_blank'>MN1</a>           |       4330 | ENSG00000169184 | AD        | NA  | MN1 proto-oncogene, transcriptional regulator                                                     | OTHER                                            | NA                                                                                                                                           |
| 217 | <a href='https://www.ncbi.nlm.nih.gov/gene/4352' target='_blank'>MPL</a>           |       4352 | ENSG00000117400 | AD        | NA  | MPL proto-oncogene, thrombopoietin receptor                                                       | CGC_94,TCGA_PANCAN_2018                          | NA                                                                                                                                           |
| 218 | <a href='https://www.ncbi.nlm.nih.gov/gene/4361' target='_blank'>MRE11</a>         |       4361 | ENSG00000020922 | NA        | NA  | MRE11 homolog, double strand break repair nuclease                                                | NCGC                                             | NA                                                                                                                                           |
| 219 | <a href='https://www.ncbi.nlm.nih.gov/gene/4436' target='_blank'>MSH2</a>          |       4436 | ENSG00000095002 | AD/AR     | LoF | mutS homolog 2                                                                                    | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary nonpolyposis colorectal neoplasms; Turcot syndrome; Hereditary nonpolyposis colon cancer; Lynch syndrome                          |
| 220 | <a href='https://www.ncbi.nlm.nih.gov/gene/4437' target='_blank'>MSH3</a>          |       4437 | ENSG00000113318 | AR        | NA  | mutS homolog 3                                                                                    | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 221 | <a href='https://www.ncbi.nlm.nih.gov/gene/4439' target='_blank'>MSH5</a>          |       4439 | ENSG00000204410 | NA        | NA  | mutS homolog 5                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 222 | <a href='https://www.ncbi.nlm.nih.gov/gene/2956' target='_blank'>MSH6</a>          |       2956 | ENSG00000116062 | AD/AR     | LoF | mutS homolog 6                                                                                    | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary nonpolyposis colorectal neoplasms; Turcot syndrome; Hereditary nonpolyposis colon cancer; Lynch syndrome                          |
| 223 | <a href='https://www.ncbi.nlm.nih.gov/gene/4481' target='_blank'>MSR1</a>          |       4481 | ENSG00000038945 | AD        | NA  | macrophage scavenger receptor 1                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 224 | <a href='https://www.ncbi.nlm.nih.gov/gene/4507' target='_blank'>MTAP</a>          |       4507 | ENSG00000099810 | AD        | LoF | methylthioadenosine phosphorylase                                                                 | PANEL_APP,TCGA_PANCAN_2018                       | Diaphyseal medullary stenosis-bone malignancy syndrome                                                                                       |
| 225 | <a href='https://www.ncbi.nlm.nih.gov/gene/4582' target='_blank'>MUC1</a>          |       4582 | ENSG00000185499 | AD        | NA  | mucin 1, cell surface associated                                                                  | OTHER                                            | NA                                                                                                                                           |
| 226 | <a href='https://www.ncbi.nlm.nih.gov/gene/727897' target='_blank'>MUC5B</a>       |     727897 | ENSG00000117983 | NA        | NA  | mucin 5B, oligomeric mucus/gel-forming                                                            | OTHER                                            | NA                                                                                                                                           |
| 227 | <a href='https://www.ncbi.nlm.nih.gov/gene/4595' target='_blank'>MUTYH</a>         |       4595 | ENSG00000132781 | AR        | LoF | mutY DNA glycosylase                                                                              | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | MYH-associated polyposis                                                                                                                     |
| 228 | <a href='https://www.ncbi.nlm.nih.gov/gene/4613' target='_blank'>MYCN</a>          |       4613 | ENSG00000134323 | NA        | NA  | MYCN proto-oncogene, bHLH transcription factor                                                    | OTHER                                            | NA                                                                                                                                           |
| 229 | <a href='https://www.ncbi.nlm.nih.gov/gene/92345' target='_blank'>NAF1</a>         |      92345 | ENSG00000145414 | AD        | NA  | nuclear assembly factor 1 ribonucleoprotein                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 230 | <a href='https://www.ncbi.nlm.nih.gov/gene/4683' target='_blank'>NBN</a>           |       4683 | ENSG00000104320 | AR        | LoF | nibrin                                                                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Microcephaly, normal intelligence and immunodeficiency                                                                                       |
| 231 | <a href='https://www.ncbi.nlm.nih.gov/gene/8031' target='_blank'>NCOA4</a>         |       8031 | ENSG00000266412 | NA        | NA  | nuclear receptor coactivator 4                                                                    | OTHER                                            | NA                                                                                                                                           |
| 232 | <a href='https://www.ncbi.nlm.nih.gov/gene/10397' target='_blank'>NDRG1</a>        |      10397 | ENSG00000104419 | NA        | NA  | N-myc downstream regulated 1                                                                      | OTHER                                            | NA                                                                                                                                           |
| 233 | <a href='https://www.ncbi.nlm.nih.gov/gene/51079' target='_blank'>NDUFA13</a>      |      51079 | ENSG00000186010 | AD        | NA  | NADH:ubiquinone oxidoreductase subunit A13                                                        | PANEL_APP                                        | NA                                                                                                                                           |
| 234 | <a href='https://www.ncbi.nlm.nih.gov/gene/4763' target='_blank'>NF1</a>           |       4763 | ENSG00000196712 | AD/AR     | LoF | neurofibromin 1                                                                                   | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Neurofibromatosis, type 1                                                                                                                    |
| 235 | <a href='https://www.ncbi.nlm.nih.gov/gene/4771' target='_blank'>NF2</a>           |       4771 | ENSG00000186575 | AD/AR     | LoF | neurofibromin 2                                                                                   | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Neurofibromatosis, type 2                                                                                                                    |
| 236 | <a href='https://www.ncbi.nlm.nih.gov/gene/4784' target='_blank'>NFIX</a>          |       4784 | ENSG00000008441 | NA        | NA  | nuclear factor I X                                                                                | PANEL_APP                                        | NA                                                                                                                                           |
| 237 | <a href='https://www.ncbi.nlm.nih.gov/gene/55651' target='_blank'>NHP2</a>         |      55651 | ENSG00000145912 | AR        | NA  | NHP2 ribonucleoprotein                                                                            | PANEL_APP,TCGA_PANCAN_2018                       | Dyskeratosis congenita, autosomal recessive 2                                                                                                |
| 238 | <a href='https://www.ncbi.nlm.nih.gov/gene/7080' target='_blank'>NKX2-1</a>        |       7080 | ENSG00000136352 | AD        | NA  | NK2 homeobox 1                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 239 | <a href='https://www.ncbi.nlm.nih.gov/gene/55505' target='_blank'>NOP10</a>        |      55505 | ENSG00000182117 | AR        | NA  | NOP10 ribonucleoprotein                                                                           | PANEL_APP,TCGA_PANCAN_2018                       | Dyskeratosis congenita autosomal recessive 1                                                                                                 |
| 240 | <a href='https://www.ncbi.nlm.nih.gov/gene/4851' target='_blank'>NOTCH1</a>        |       4851 | ENSG00000148400 | NA        | NA  | notch receptor 1                                                                                  | OTHER                                            | NA                                                                                                                                           |
| 241 | <a href='https://www.ncbi.nlm.nih.gov/gene/4854' target='_blank'>NOTCH3</a>        |       4854 | ENSG00000074181 | AD        | NA  | notch receptor 3                                                                                  | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 242 | <a href='https://www.ncbi.nlm.nih.gov/gene/8013' target='_blank'>NR4A3</a>         |       8013 | ENSG00000119508 | NA        | NA  | nuclear receptor subfamily 4 group A member 3                                                     | OTHER                                            | NA                                                                                                                                           |
| 243 | <a href='https://www.ncbi.nlm.nih.gov/gene/4893' target='_blank'>NRAS</a>          |       4893 | ENSG00000213281 | AD        | NA  | NRAS proto-oncogene, GTPase                                                                       | PANEL_APP,TCGA_PANCAN_2018                       | NA; Epidermal nevus; Large congenital melanocytic nevus; RAS-associated autoimmune leukoproliferative disorder; Noonan syndrome 6; Rasopathy |
| 244 | <a href='https://www.ncbi.nlm.nih.gov/gene/64324' target='_blank'>NSD1</a>         |      64324 | ENSG00000165671 | AD        | LoF | nuclear receptor binding SET domain protein 1                                                     | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 245 | <a href='https://www.ncbi.nlm.nih.gov/gene/4913' target='_blank'>NTHL1</a>         |       4913 | ENSG00000065057 | AR        | NA  | nth like DNA glycosylase 1                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Familial adenomatous polyposis 3                                                                                                             |
| 246 | <a href='https://www.ncbi.nlm.nih.gov/gene/4914' target='_blank'>NTRK1</a>         |       4914 | ENSG00000198400 | AD        | NA  | neurotrophic receptor tyrosine kinase 1                                                           | PANEL_APP                                        | NA                                                                                                                                           |
| 247 | <a href='https://www.ncbi.nlm.nih.gov/gene/4916' target='_blank'>NTRK3</a>         |       4916 | ENSG00000140538 | NA        | NA  | neurotrophic receptor tyrosine kinase 3                                                           | OTHER                                            | NA                                                                                                                                           |
| 248 | <a href='https://www.ncbi.nlm.nih.gov/gene/57523' target='_blank'>NYNRIN</a>       |      57523 | ENSG00000205978 | NA        | NA  | NYN domain and retroviral integrase containing                                                    | OTHER                                            | NA                                                                                                                                           |
| 249 | <a href='https://www.ncbi.nlm.nih.gov/gene/4968' target='_blank'>OGG1</a>          |       4968 | ENSG00000114026 | NA        | NA  | 8-oxoguanine DNA glycosylase                                                                      | NCGC                                             | NA                                                                                                                                           |
| 250 | <a href='https://www.ncbi.nlm.nih.gov/gene/79728' target='_blank'>PALB2</a>        |      79728 | ENSG00000083093 | AD/AR     | LoF | partner and localizer of BRCA2                                                                    | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Familial cancer of breast; Fanconi anemia, complementation group N                                                                           |
| 251 | <a href='https://www.ncbi.nlm.nih.gov/gene/5073' target='_blank'>PARN</a>          |       5073 | ENSG00000140694 | AD/AR     | NA  | poly(A)-specific ribonuclease                                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 252 | <a href='https://www.ncbi.nlm.nih.gov/gene/5077' target='_blank'>PAX3</a>          |       5077 | ENSG00000135903 | NA        | NA  | paired box 3                                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 253 | <a href='https://www.ncbi.nlm.nih.gov/gene/5079' target='_blank'>PAX5</a>          |       5079 | ENSG00000196092 | AD        | NA  | paired box 5                                                                                      | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Leukemia, acute lymphoblastic, susceptibility to, 3                                                                                          |
| 254 | <a href='https://www.ncbi.nlm.nih.gov/gene/5080' target='_blank'>PAX6</a>          |       5080 | ENSG00000007372 | AD        | NA  | paired box 6                                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 255 | <a href='https://www.ncbi.nlm.nih.gov/gene/5081' target='_blank'>PAX7</a>          |       5081 | ENSG00000009709 | NA        | NA  | paired box 7                                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 256 | <a href='https://www.ncbi.nlm.nih.gov/gene/55193' target='_blank'>PBRM1</a>        |      55193 | ENSG00000163939 | NA        | NA  | polybromo 1                                                                                       | OTHER                                            | NA                                                                                                                                           |
| 257 | <a href='https://www.ncbi.nlm.nih.gov/gene/5156' target='_blank'>PDGFRA</a>        |       5156 | ENSG00000134853 | AD        | GoF | platelet derived growth factor receptor alpha                                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Gastrointestinal stromal tumor                                                                                                               |
| 258 | <a href='https://www.ncbi.nlm.nih.gov/gene/5159' target='_blank'>PDGFRB</a>        |       5159 | ENSG00000113721 | AD        | NA  | platelet derived growth factor receptor beta                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 259 | <a href='https://www.ncbi.nlm.nih.gov/gene/84295' target='_blank'>PHF6</a>         |      84295 | ENSG00000156531 | NA        | NA  | PHD finger protein 6                                                                              | OTHER                                            | NA                                                                                                                                           |
| 260 | <a href='https://www.ncbi.nlm.nih.gov/gene/8929' target='_blank'>PHOX2B</a>        |       8929 | ENSG00000109132 | AD/AR     | LoF | paired like homeobox 2B                                                                           | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Neuroblastoma 2                                                                                                                              |
| 261 | <a href='https://www.ncbi.nlm.nih.gov/gene/5290' target='_blank'>PIK3CA</a>        |       5290 | ENSG00000121879 | AD        | GoF | phosphatidylinositol-4,5-bisphosphate 3-kinase catalytic subunit alpha                            | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 262 | <a href='https://www.ncbi.nlm.nih.gov/gene/65018' target='_blank'>PINK1</a>        |      65018 | ENSG00000158828 | NA        | NA  | PTEN induced kinase 1                                                                             | NCGC                                             | NA                                                                                                                                           |
| 263 | <a href='https://www.ncbi.nlm.nih.gov/gene/5371' target='_blank'>PML</a>           |       5371 | ENSG00000140464 | NA        | NA  | PML nuclear body scaffold                                                                         | OTHER                                            | NA                                                                                                                                           |
| 264 | <a href='https://www.ncbi.nlm.nih.gov/gene/5378' target='_blank'>PMS1</a>          |       5378 | ENSG00000064933 | AR        | NA  | PMS1 homolog 1, mismatch repair system component                                                  | CGC_94,NCGC,TCGA_PANCAN_2018                     | NA                                                                                                                                           |
| 265 | <a href='https://www.ncbi.nlm.nih.gov/gene/5395' target='_blank'>PMS2</a>          |       5395 | ENSG00000122512 | AD/AR     | LoF | PMS1 homolog 2, mismatch repair system component                                                  | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary nonpolyposis colorectal neoplasms; Turcot syndrome; Hereditary nonpolyposis colon cancer; Lynch syndrome                          |
| 266 | <a href='https://www.ncbi.nlm.nih.gov/gene/5422' target='_blank'>POLA1</a>         |       5422 | ENSG00000101868 | NA        | NA  | DNA polymerase alpha 1, catalytic subunit                                                         | PANEL_APP                                        | NA                                                                                                                                           |
| 267 | <a href='https://www.ncbi.nlm.nih.gov/gene/5424' target='_blank'>POLD1</a>         |       5424 | ENSG00000062822 | AD        | LoF | DNA polymerase delta 1, catalytic subunit                                                         | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | NA                                                                                                                                           |
| 268 | <a href='https://www.ncbi.nlm.nih.gov/gene/5426' target='_blank'>POLE</a>          |       5426 | ENSG00000177084 | AD/AR     | LoF | DNA polymerase epsilon, catalytic subunit                                                         | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | NA                                                                                                                                           |
| 269 | <a href='https://www.ncbi.nlm.nih.gov/gene/5429' target='_blank'>POLH</a>          |       5429 | ENSG00000170734 | AR        | LoF | DNA polymerase eta                                                                                | PANEL_APP,TCGA_PANCAN_2018                       | Xeroderma pigmentosum variant type                                                                                                           |
| 270 | <a href='https://www.ncbi.nlm.nih.gov/gene/10721' target='_blank'>POLQ</a>         |      10721 | ENSG00000051341 | NA        | NA  | DNA polymerase theta                                                                              | CGC_94                                           | NA                                                                                                                                           |
| 271 | <a href='https://www.ncbi.nlm.nih.gov/gene/64840' target='_blank'>PORCN</a>        |      64840 | ENSG00000102312 | NA        | NA  | porcupine O-acyltransferase                                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 272 | <a href='https://www.ncbi.nlm.nih.gov/gene/25913' target='_blank'>POT1</a>         |      25913 | ENSG00000128513 | AD        | NA  | protection of telomeres 1                                                                         | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Melanoma, cutaneous malignant, susceptibility to, 10                                                                                         |
| 273 | <a href='https://www.ncbi.nlm.nih.gov/gene/8493' target='_blank'>PPM1D</a>         |       8493 | ENSG00000170836 | NA        | LoF | protein phosphatase, Mg2+/Mn2+ dependent 1D                                                       | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 274 | <a href='https://www.ncbi.nlm.nih.gov/gene/5500' target='_blank'>PPP1CB</a>        |       5500 | ENSG00000213639 | AD        | NA  | protein phosphatase 1 catalytic subunit beta                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 275 | <a href='https://www.ncbi.nlm.nih.gov/gene/639' target='_blank'>PRDM1</a>          |        639 | ENSG00000057657 | NA        | NA  | PR/SET domain 1                                                                                   | OTHER                                            | NA                                                                                                                                           |
| 276 | <a href='https://www.ncbi.nlm.nih.gov/gene/56979' target='_blank'>PRDM9</a>        |      56979 | ENSG00000164256 | AD        | NA  | PR/SET domain 9                                                                                   | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 277 | <a href='https://www.ncbi.nlm.nih.gov/gene/5551' target='_blank'>PRF1</a>          |       5551 | ENSG00000180644 | AR        | LoF | perforin 1                                                                                        | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Familial hemophagocytic lymphohistiocytosis 2                                                                                                |
| 278 | <a href='https://www.ncbi.nlm.nih.gov/gene/5573' target='_blank'>PRKAR1A</a>       |       5573 | ENSG00000108946 | AD/AR     | LoF | protein kinase cAMP-dependent type I regulatory subunit alpha                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Carney complex                                                                                                                               |
| 279 | <a href='https://www.ncbi.nlm.nih.gov/gene/5071' target='_blank'>PRKN</a>          |       5071 | ENSG00000185345 | NA        | NA  | parkin RBR E3 ubiquitin protein ligase                                                            | OTHER                                            | NA                                                                                                                                           |
| 280 | <a href='https://www.ncbi.nlm.nih.gov/gene/5644' target='_blank'>PRSS1</a>         |       5644 | ENSG00000204983 | AD        | LoF | serine protease 1                                                                                 | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Hereditary pancreatitis                                                                                                                      |
| 281 | <a href='https://www.ncbi.nlm.nih.gov/gene/5727' target='_blank'>PTCH1</a>         |       5727 | ENSG00000185920 | AD/AR     | LoF | patched 1                                                                                         | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Gorlin syndrome                                                                                                                              |
| 282 | <a href='https://www.ncbi.nlm.nih.gov/gene/8643' target='_blank'>PTCH2</a>         |       8643 | ENSG00000117425 | AD        | NA  | patched 2                                                                                         | PANEL_APP                                        | NA                                                                                                                                           |
| 283 | <a href='https://www.ncbi.nlm.nih.gov/gene/100302522' target='_blank'>PTCSC1</a>   |  100302522 | ENSG00000287736 | AD        | NA  | papillary thyroid carcinoma susceptibility candidate 1                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 284 | <a href='https://www.ncbi.nlm.nih.gov/gene/100886964' target='_blank'>PTCSC3</a>   |  100886964 | NA              | NA        | NA  | papillary thyroid carcinoma susceptibility candidate 3                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 285 | <a href='https://www.ncbi.nlm.nih.gov/gene/5728' target='_blank'>PTEN</a>          |       5728 | ENSG00000171862 | AD/AR     | LoF | phosphatase and tensin homolog                                                                    | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | PTEN hamartoma tumor syndrome; Cowden syndrome 1                                                                                             |
| 286 | <a href='https://www.ncbi.nlm.nih.gov/gene/5781' target='_blank'>PTPN11</a>        |       5781 | ENSG00000179295 | AD        | GoF | protein tyrosine phosphatase non-receptor type 11                                                 | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Noonan syndrome                                                                                                                              |
| 287 | <a href='https://www.ncbi.nlm.nih.gov/gene/5782' target='_blank'>PTPN12</a>        |       5782 | ENSG00000127947 | NA        | NA  | protein tyrosine phosphatase non-receptor type 12                                                 | PANEL_APP                                        | NA                                                                                                                                           |
| 288 | <a href='https://www.ncbi.nlm.nih.gov/gene/5783' target='_blank'>PTPN13</a>        |       5783 | ENSG00000163629 | AR        | NA  | protein tyrosine phosphatase non-receptor type 13                                                 | CGC_94                                           | NA                                                                                                                                           |
| 289 | <a href='https://www.ncbi.nlm.nih.gov/gene/5795' target='_blank'>PTPRJ</a>         |       5795 | ENSG00000149177 | NA        | NA  | protein tyrosine phosphatase receptor type J                                                      | OTHER                                            | NA                                                                                                                                           |
| 290 | <a href='https://www.ncbi.nlm.nih.gov/gene/285282' target='_blank'>RABL3</a>       |     285282 | ENSG00000144840 | AD        | NA  | RAB, member of RAS oncogene family like 3                                                         | PANEL_APP                                        | NA                                                                                                                                           |
| 291 | <a href='https://www.ncbi.nlm.nih.gov/gene/10111' target='_blank'>RAD50</a>        |      10111 | ENSG00000113522 | AD/AR     | LoF | RAD50 double strand break repair protein                                                          | NCGC                                             | NA                                                                                                                                           |
| 292 | <a href='https://www.ncbi.nlm.nih.gov/gene/5888' target='_blank'>RAD51</a>         |       5888 | ENSG00000051180 | AD        | NA  | RAD51 recombinase                                                                                 | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 293 | <a href='https://www.ncbi.nlm.nih.gov/gene/5890' target='_blank'>RAD51B</a>        |       5890 | ENSG00000182185 | NA        | NA  | RAD51 paralog B                                                                                   | NCGC                                             | NA                                                                                                                                           |
| 294 | <a href='https://www.ncbi.nlm.nih.gov/gene/5889' target='_blank'>RAD51C</a>        |       5889 | ENSG00000108384 | AD/AR     | LoF | RAD51 paralog C                                                                                   | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Fanconi anemia, complementation group O                                                                                                      |
| 295 | <a href='https://www.ncbi.nlm.nih.gov/gene/5892' target='_blank'>RAD51D</a>        |       5892 | ENSG00000185379 | AD        | LoF | RAD51 paralog D                                                                                   | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Breast-ovarian cancer, familial 4                                                                                                            |
| 296 | <a href='https://www.ncbi.nlm.nih.gov/gene/8438' target='_blank'>RAD54L</a>        |       8438 | ENSG00000085999 | NA        | NA  | RAD54 like                                                                                        | PANEL_APP                                        | NA                                                                                                                                           |
| 297 | <a href='https://www.ncbi.nlm.nih.gov/gene/5894' target='_blank'>RAF1</a>          |       5894 | ENSG00000132155 | AD        | NA  | Raf-1 proto-oncogene, serine/threonine kinase                                                     | PANEL_APP,TCGA_PANCAN_2018                       | LEOPARD syndrome 2; Noonan syndrome 5                                                                                                        |
| 298 | <a href='https://www.ncbi.nlm.nih.gov/gene/5921' target='_blank'>RASA1</a>         |       5921 | ENSG00000145715 | NA        | NA  | RAS p21 protein activator 1                                                                       | OTHER                                            | NA                                                                                                                                           |
| 299 | <a href='https://www.ncbi.nlm.nih.gov/gene/5925' target='_blank'>RB1</a>           |       5925 | ENSG00000139687 | AD/AR     | LoF | RB transcriptional corepressor 1                                                                  | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Osteosarcoma; Retinoblastoma                                                                                                                 |
| 300 | <a href='https://www.ncbi.nlm.nih.gov/gene/55920' target='_blank'>RCC2</a>         |      55920 | ENSG00000179051 | NA        | NA  | regulator of chromosome condensation 2                                                            | NCGC                                             | NA                                                                                                                                           |
| 301 | <a href='https://www.ncbi.nlm.nih.gov/gene/5965' target='_blank'>RECQL</a>         |       5965 | ENSG00000004700 | AD        | NA  | RecQ like helicase                                                                                | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 302 | <a href='https://www.ncbi.nlm.nih.gov/gene/9401' target='_blank'>RECQL4</a>        |       9401 | ENSG00000160957 | AR        | LoF | RecQ like helicase 4                                                                              | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Rothmund-Thomson syndrome                                                                                                                    |
| 303 | <a href='https://www.ncbi.nlm.nih.gov/gene/5978' target='_blank'>REST</a>          |       5978 | ENSG00000084093 | AD        | NA  | RE1 silencing transcription factor                                                                | PANEL_APP                                        | NA                                                                                                                                           |
| 304 | <a href='https://www.ncbi.nlm.nih.gov/gene/5979' target='_blank'>RET</a>           |       5979 | ENSG00000165731 | AD        | GoF | ret proto-oncogene                                                                                | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Multiple endocrine neoplasia, type 2a; Multiple endocrine neoplasia, type 2b; Familial medullary thyroid carcinoma                           |
| 305 | <a href='https://www.ncbi.nlm.nih.gov/gene/55159' target='_blank'>RFWD3</a>        |      55159 | ENSG00000168411 | NA        | NA  | ring finger and WD repeat domain 3                                                                | CGC_94                                           | NA                                                                                                                                           |
| 306 | <a href='https://www.ncbi.nlm.nih.gov/gene/79651' target='_blank'>RHBDF2</a>       |      79651 | ENSG00000129667 | AD        | GoF | rhomboid 5 homolog 2                                                                              | NCGC,TCGA_PANCAN_2018                            | Palmoplantar keratoderma-esophageal carcinoma syndrome                                                                                       |
| 307 | <a href='https://www.ncbi.nlm.nih.gov/gene/6015' target='_blank'>RING1</a>         |       6015 | ENSG00000204227 | NA        | NA  | ring finger protein 1                                                                             | NCGC                                             | NA                                                                                                                                           |
| 308 | <a href='https://www.ncbi.nlm.nih.gov/gene/60561' target='_blank'>RINT1</a>        |      60561 | ENSG00000135249 | NA        | NA  | RAD50 interactor 1                                                                                | NCGC                                             | NA                                                                                                                                           |
| 309 | <a href='https://www.ncbi.nlm.nih.gov/gene/6016' target='_blank'>RIT1</a>          |       6016 | ENSG00000143622 | AD        | NA  | Ras like without CAAX 1                                                                           | PANEL_APP                                        | NA                                                                                                                                           |
| 310 | <a href='https://www.ncbi.nlm.nih.gov/gene/6023' target='_blank'>RMRP</a>          |       6023 | ENSG00000269900 | AR        | LoF | RNA component of mitochondrial RNA processing endoribonuclease                                    | PANEL_APP,TCGA_PANCAN_2018                       | Metaphyseal chondrodysplasia, McKusick type                                                                                                  |
| 311 | <a href='https://www.ncbi.nlm.nih.gov/gene/6041' target='_blank'>RNASEL</a>        |       6041 | ENSG00000135828 | NA        | NA  | ribonuclease L                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 312 | <a href='https://www.ncbi.nlm.nih.gov/gene/54894' target='_blank'>RNF43</a>        |      54894 | ENSG00000108375 | AD        | NA  | ring finger protein 43                                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 313 | <a href='https://www.ncbi.nlm.nih.gov/gene/6098' target='_blank'>ROS1</a>          |       6098 | ENSG00000047936 | NA        | NA  | ROS proto-oncogene 1, receptor tyrosine kinase                                                    | OTHER                                            | NA                                                                                                                                           |
| 314 | <a href='https://www.ncbi.nlm.nih.gov/gene/6135' target='_blank'>RPL11</a>         |       6135 | ENSG00000142676 | AD        | NA  | ribosomal protein L11                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 315 | <a href='https://www.ncbi.nlm.nih.gov/gene/6138' target='_blank'>RPL15</a>         |       6138 | ENSG00000174748 | AD        | NA  | ribosomal protein L15                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 316 | <a href='https://www.ncbi.nlm.nih.gov/gene/9349' target='_blank'>RPL23</a>         |       9349 | ENSG00000125691 | AD        | NA  | ribosomal protein L23                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 317 | <a href='https://www.ncbi.nlm.nih.gov/gene/6154' target='_blank'>RPL26</a>         |       6154 | ENSG00000161970 | AD        | NA  | ribosomal protein L26                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 318 | <a href='https://www.ncbi.nlm.nih.gov/gene/6155' target='_blank'>RPL27</a>         |       6155 | ENSG00000131469 | AD        | NA  | ribosomal protein L27                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 319 | <a href='https://www.ncbi.nlm.nih.gov/gene/6160' target='_blank'>RPL31</a>         |       6160 | ENSG00000071082 | AD        | NA  | ribosomal protein L31                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 320 | <a href='https://www.ncbi.nlm.nih.gov/gene/6165' target='_blank'>RPL35A</a>        |       6165 | ENSG00000182899 | AD        | NA  | ribosomal protein L35a                                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 321 | <a href='https://www.ncbi.nlm.nih.gov/gene/25873' target='_blank'>RPL36</a>        |      25873 | ENSG00000130255 | AD        | NA  | ribosomal protein L36                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 322 | <a href='https://www.ncbi.nlm.nih.gov/gene/6125' target='_blank'>RPL5</a>          |       6125 | ENSG00000122406 | AD        | NA  | ribosomal protein L5                                                                              | PANEL_APP                                        | NA                                                                                                                                           |
| 323 | <a href='https://www.ncbi.nlm.nih.gov/gene/6204' target='_blank'>RPS10</a>         |       6204 | ENSG00000124614 | AD        | NA  | ribosomal protein S10                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 324 | <a href='https://www.ncbi.nlm.nih.gov/gene/6209' target='_blank'>RPS15</a>         |       6209 | ENSG00000115268 | AD        | NA  | ribosomal protein S15                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 325 | <a href='https://www.ncbi.nlm.nih.gov/gene/6218' target='_blank'>RPS17</a>         |       6218 | ENSG00000182774 | AD        | NA  | ribosomal protein S17                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 326 | <a href='https://www.ncbi.nlm.nih.gov/gene/6223' target='_blank'>RPS19</a>         |       6223 | ENSG00000105372 | AD        | NA  | ribosomal protein S19                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 327 | <a href='https://www.ncbi.nlm.nih.gov/gene/6229' target='_blank'>RPS24</a>         |       6229 | ENSG00000138326 | AD        | NA  | ribosomal protein S24                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 328 | <a href='https://www.ncbi.nlm.nih.gov/gene/6231' target='_blank'>RPS26</a>         |       6231 | ENSG00000197728 | AD        | NA  | ribosomal protein S26                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 329 | <a href='https://www.ncbi.nlm.nih.gov/gene/6232' target='_blank'>RPS27</a>         |       6232 | ENSG00000177954 | AD        | NA  | ribosomal protein S27                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 330 | <a href='https://www.ncbi.nlm.nih.gov/gene/6233' target='_blank'>RPS27A</a>        |       6233 | ENSG00000143947 | AD        | NA  | ribosomal protein S27a                                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 331 | <a href='https://www.ncbi.nlm.nih.gov/gene/6234' target='_blank'>RPS28</a>         |       6234 | ENSG00000233927 | AD        | NA  | ribosomal protein S28                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 332 | <a href='https://www.ncbi.nlm.nih.gov/gene/6235' target='_blank'>RPS29</a>         |       6235 | ENSG00000213741 | AD        | NA  | ribosomal protein S29                                                                             | PANEL_APP                                        | NA                                                                                                                                           |
| 333 | <a href='https://www.ncbi.nlm.nih.gov/gene/6201' target='_blank'>RPS7</a>          |       6201 | ENSG00000171863 | AD        | NA  | ribosomal protein S7                                                                              | PANEL_APP                                        | NA                                                                                                                                           |
| 334 | <a href='https://www.ncbi.nlm.nih.gov/gene/22800' target='_blank'>RRAS2</a>        |      22800 | ENSG00000133818 | NA        | NA  | RAS related 2                                                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 335 | <a href='https://www.ncbi.nlm.nih.gov/gene/51750' target='_blank'>RTEL1</a>        |      51750 | ENSG00000258366 | AD/AR     | NA  | regulator of telomere elongation helicase 1                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 336 | <a href='https://www.ncbi.nlm.nih.gov/gene/861' target='_blank'>RUNX1</a>          |        861 | NA              | AD        | LoF | RUNX family transcription factor 1                                                                | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Familial platelet disorder with associated myeloid malignancy                                                                                |
| 337 | <a href='https://www.ncbi.nlm.nih.gov/gene/54809' target='_blank'>SAMD9</a>        |      54809 | ENSG00000205413 | AD/AR     | NA  | sterile alpha motif domain containing 9                                                           | PANEL_APP                                        | NA                                                                                                                                           |
| 338 | <a href='https://www.ncbi.nlm.nih.gov/gene/219285' target='_blank'>SAMD9L</a>      |     219285 | ENSG00000177409 | AD        | NA  | sterile alpha motif domain containing 9 like                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 339 | <a href='https://www.ncbi.nlm.nih.gov/gene/23328' target='_blank'>SASH1</a>        |      23328 | ENSG00000111961 | AD/AR     | NA  | SAM and SH3 domain containing 1                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 340 | <a href='https://www.ncbi.nlm.nih.gov/gene/51119' target='_blank'>SBDS</a>         |      51119 | ENSG00000126524 | AR        | LoF | SBDS ribosome maturation factor                                                                   | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Shwachman syndrome                                                                                                                           |
| 341 | <a href='https://www.ncbi.nlm.nih.gov/gene/6447' target='_blank'>SCG5</a>          |       6447 | ENSG00000166922 | NA        | NA  | secretogranin V                                                                                   | NCGC                                             | NA                                                                                                                                           |
| 342 | <a href='https://www.ncbi.nlm.nih.gov/gene/6389' target='_blank'>SDHA</a>          |       6389 | ENSG00000073578 | AD/AR     | LoF | succinate dehydrogenase complex flavoprotein subunit A                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Paragangliomas 5                                                                                                                             |
| 343 | <a href='https://www.ncbi.nlm.nih.gov/gene/54949' target='_blank'>SDHAF2</a>       |      54949 | ENSG00000167985 | AD/AR     | LoF | succinate dehydrogenase complex assembly factor 2                                                 | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary Paraganglioma-Pheochromocytoma Syndromes                                                                                          |
| 344 | <a href='https://www.ncbi.nlm.nih.gov/gene/6390' target='_blank'>SDHB</a>          |       6390 | ENSG00000117118 | AD/AR     | LoF | succinate dehydrogenase complex iron sulfur subunit B                                             | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary Paraganglioma-Pheochromocytoma Syndromes; Carney-Stratakis syndrome                                                               |
| 345 | <a href='https://www.ncbi.nlm.nih.gov/gene/6391' target='_blank'>SDHC</a>          |       6391 | ENSG00000143252 | AD/AR     | LoF | succinate dehydrogenase complex subunit C                                                         | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary Paraganglioma-Pheochromocytoma Syndromes; Carney-Stratakis syndrome                                                               |
| 346 | <a href='https://www.ncbi.nlm.nih.gov/gene/6392' target='_blank'>SDHD</a>          |       6392 | ENSG00000204370 | AD/AR     | LoF | succinate dehydrogenase complex subunit D                                                         | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary Paraganglioma-Pheochromocytoma Syndromes; Carney-Stratakis syndrome                                                               |
| 347 | <a href='https://www.ncbi.nlm.nih.gov/gene/10483' target='_blank'>SEC23B</a>       |      10483 | ENSG00000101310 | AD        | NA  | SEC23 homolog B, COPII coat complex component                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 348 | <a href='https://www.ncbi.nlm.nih.gov/gene/64218' target='_blank'>SEMA4A</a>       |      64218 | ENSG00000196189 | NA        | NA  | semaphorin 4A                                                                                     | OTHER                                            | NA                                                                                                                                           |
| 349 | <a href='https://www.ncbi.nlm.nih.gov/gene/5265' target='_blank'>SERPINA1</a>      |       5265 | ENSG00000197249 | AR        | LoF | serpin family A member 1                                                                          | OTHER,TCGA_PANCAN_2018                           | Alpha-1-antitrypsin deficiency                                                                                                               |
| 350 | <a href='https://www.ncbi.nlm.nih.gov/gene/26040' target='_blank'>SETBP1</a>       |      26040 | ENSG00000152217 | AD        | NA  | SET binding protein 1                                                                             | CGC_94,TCGA_PANCAN_2018                          | Schinzel-Giedion syndrome                                                                                                                    |
| 351 | <a href='https://www.ncbi.nlm.nih.gov/gene/6419' target='_blank'>SETMAR</a>        |       6419 | ENSG00000170364 | NA        | NA  | SET domain and mariner transposase fusion gene                                                    | OTHER                                            | NA                                                                                                                                           |
| 352 | <a href='https://www.ncbi.nlm.nih.gov/gene/653509' target='_blank'>SFTPA1</a>      |     653509 | ENSG00000122852 | NA        | NA  | surfactant protein A1                                                                             | OTHER                                            | NA                                                                                                                                           |
| 353 | <a href='https://www.ncbi.nlm.nih.gov/gene/729238' target='_blank'>SFTPA2</a>      |     729238 | ENSG00000185303 | NA        | NA  | surfactant protein A2                                                                             | OTHER                                            | NA                                                                                                                                           |
| 354 | <a href='https://www.ncbi.nlm.nih.gov/gene/10019' target='_blank'>SH2B3</a>        |      10019 | ENSG00000111252 | AR        | NA  | SH2B adaptor protein 3                                                                            | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 355 | <a href='https://www.ncbi.nlm.nih.gov/gene/4068' target='_blank'>SH2D1A</a>        |       4068 | ENSG00000183918 | NA        | LoF | SH2 domain containing 1A                                                                          | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 356 | <a href='https://www.ncbi.nlm.nih.gov/gene/8036' target='_blank'>SHOC2</a>         |       8036 | ENSG00000108061 | AD        | NA  | SHOC2 leucine rich repeat scaffold protein                                                        | PANEL_APP,TCGA_PANCAN_2018                       | Noonan syndrome-like disorder with loose anagen hair                                                                                         |
| 357 | <a href='https://www.ncbi.nlm.nih.gov/gene/6495' target='_blank'>SIX1</a>          |       6495 | ENSG00000126778 | NA        | NA  | SIX homeobox 1                                                                                    | OTHER                                            | NA                                                                                                                                           |
| 358 | <a href='https://www.ncbi.nlm.nih.gov/gene/10165' target='_blank'>SLC25A13</a>     |      10165 | ENSG00000004864 | AR        | LoF | solute carrier family 25 member 13                                                                | TCGA_PANCAN_2018                                 | NA                                                                                                                                           |
| 359 | <a href='https://www.ncbi.nlm.nih.gov/gene/1811' target='_blank'>SLC26A3</a>       |       1811 | ENSG00000091138 | NA        | NA  | solute carrier family 26 member 3                                                                 | PANEL_APP                                        | NA                                                                                                                                           |
| 360 | <a href='https://www.ncbi.nlm.nih.gov/gene/6528' target='_blank'>SLC5A5</a>        |       6528 | ENSG00000105641 | AR        | NA  | solute carrier family 5 member 5                                                                  | PANEL_APP                                        | NA                                                                                                                                           |
| 361 | <a href='https://www.ncbi.nlm.nih.gov/gene/84464' target='_blank'>SLX4</a>         |      84464 | ENSG00000188827 | AR        | LoF | SLX4 structure-specific endonuclease subunit                                                      | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 362 | <a href='https://www.ncbi.nlm.nih.gov/gene/4089' target='_blank'>SMAD4</a>         |       4089 | ENSG00000141646 | AD/AR     | LoF | SMAD family member 4                                                                              | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Hereditary hemorrhagic telangiectasia; Juvenile polyposis syndrome                                                                           |
| 363 | <a href='https://www.ncbi.nlm.nih.gov/gene/4093' target='_blank'>SMAD9</a>         |       4093 | ENSG00000120693 | AD        | NA  | SMAD family member 9                                                                              | PANEL_APP                                        | NA                                                                                                                                           |
| 364 | <a href='https://www.ncbi.nlm.nih.gov/gene/6595' target='_blank'>SMARCA2</a>       |       6595 | ENSG00000080503 | AR        | NA  | SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily a, member 2 | OTHER                                            | NA                                                                                                                                           |
| 365 | <a href='https://www.ncbi.nlm.nih.gov/gene/6597' target='_blank'>SMARCA4</a>       |       6597 | ENSG00000127616 | AD/AR     | LoF | SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily a, member 4 | NCGC,PANEL_APP,TCGA_PANCAN_2018                  | Rhabdoid tumor predisposition syndrome 2                                                                                                     |
| 366 | <a href='https://www.ncbi.nlm.nih.gov/gene/6598' target='_blank'>SMARCB1</a>       |       6598 | ENSG00000099956 | AD/AR     | LoF | SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily b, member 1 | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Rhabdoid tumor predisposition syndrome 1                                                                                                     |
| 367 | <a href='https://www.ncbi.nlm.nih.gov/gene/6605' target='_blank'>SMARCE1</a>       |       6605 | ENSG00000073584 | AD/AR     | LoF | SWI/SNF related, matrix associated, actin dependent regulator of chromatin, subfamily e, member 1 | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Hereditary Meningioma                                                                                                                        |
| 368 | <a href='https://www.ncbi.nlm.nih.gov/gene/6608' target='_blank'>SMO</a>           |       6608 | ENSG00000128602 | NA        | NA  | smoothened, frizzled class receptor                                                               | OTHER                                            | NA                                                                                                                                           |
| 369 | <a href='https://www.ncbi.nlm.nih.gov/gene/8651' target='_blank'>SOCS1</a>         |       8651 | ENSG00000185338 | NA        | NA  | suppressor of cytokine signaling 1                                                                | OTHER                                            | NA                                                                                                                                           |
| 370 | <a href='https://www.ncbi.nlm.nih.gov/gene/6654' target='_blank'>SOS1</a>          |       6654 | ENSG00000115904 | AD        | GoF | SOS Ras/Rac guanine nucleotide exchange factor 1                                                  | PANEL_APP,TCGA_PANCAN_2018                       | Noonan syndrome                                                                                                                              |
| 371 | <a href='https://www.ncbi.nlm.nih.gov/gene/6655' target='_blank'>SOS2</a>          |       6655 | ENSG00000100485 | AD        | NA  | SOS Ras/Rho guanine nucleotide exchange factor 2                                                  | PANEL_APP                                        | NA                                                                                                                                           |
| 372 | <a href='https://www.ncbi.nlm.nih.gov/gene/6690' target='_blank'>SPINK1</a>        |       6690 | ENSG00000164266 | NA        | NA  | serine peptidase inhibitor Kazal type 1                                                           | NCGC                                             | NA                                                                                                                                           |
| 373 | <a href='https://www.ncbi.nlm.nih.gov/gene/8405' target='_blank'>SPOP</a>          |       8405 | ENSG00000121067 | AR        | NA  | speckle type BTB/POZ protein                                                                      | CGC_94,PANEL_APP                                 | NA                                                                                                                                           |
| 374 | <a href='https://www.ncbi.nlm.nih.gov/gene/161742' target='_blank'>SPRED1</a>      |     161742 | ENSG00000166068 | AD        | NA  | sprouty related EVH1 domain containing 1                                                          | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 375 | <a href='https://www.ncbi.nlm.nih.gov/gene/83932' target='_blank'>SPRTN</a>        |      83932 | ENSG00000010072 | AR        | NA  | SprT-like N-terminal domain                                                                       | TCGA_PANCAN_2018                                 | Ruijs-Aalfs syndrome                                                                                                                         |
| 376 | <a href='https://www.ncbi.nlm.nih.gov/gene/8878' target='_blank'>SQSTM1</a>        |       8878 | ENSG00000161011 | AD        | NA  | sequestosome 1                                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 377 | <a href='https://www.ncbi.nlm.nih.gov/gene/6714' target='_blank'>SRC</a>           |       6714 | ENSG00000197122 | NA        | NA  | SRC proto-oncogene, non-receptor tyrosine kinase                                                  | PANEL_APP                                        | NA                                                                                                                                           |
| 378 | <a href='https://www.ncbi.nlm.nih.gov/gene/57522' target='_blank'>SRGAP1</a>       |      57522 | ENSG00000196935 | AD        | NA  | SLIT-ROBO Rho GTPase activating protein 1                                                         | PANEL_APP                                        | NA                                                                                                                                           |
| 379 | <a href='https://www.ncbi.nlm.nih.gov/gene/6731' target='_blank'>SRP72</a>         |       6731 | ENSG00000174780 | AD        | NA  | signal recognition particle 72                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 380 | <a href='https://www.ncbi.nlm.nih.gov/gene/23524' target='_blank'>SRRM2</a>        |      23524 | ENSG00000167978 | AD        | NA  | serine/arginine repetitive matrix 2                                                               | PANEL_APP                                        | NA                                                                                                                                           |
| 381 | <a href='https://www.ncbi.nlm.nih.gov/gene/6736' target='_blank'>SRY</a>           |       6736 | ENSG00000184895 | NA        | NA  | sex determining region Y                                                                          | TCGA_PANCAN_2018                                 | Gonadoblastoma                                                                                                                               |
| 382 | <a href='https://www.ncbi.nlm.nih.gov/gene/6774' target='_blank'>STAT3</a>         |       6774 | ENSG00000168610 | AD        | LoF | signal transducer and activator of transcription 3                                                | CGC_94,PANEL_APP,TCGA_PANCAN_2018                | STAT3 Deficiency                                                                                                                             |
| 383 | <a href='https://www.ncbi.nlm.nih.gov/gene/6794' target='_blank'>STK11</a>         |       6794 | ENSG00000118046 | AD/AR     | LoF | serine/threonine kinase 11                                                                        | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Peutz-Jeghers syndrome                                                                                                                       |
| 384 | <a href='https://www.ncbi.nlm.nih.gov/gene/79991' target='_blank'>STN1</a>         |      79991 | ENSG00000107960 | AD        | NA  | STN1 subunit of CST complex                                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 385 | <a href='https://www.ncbi.nlm.nih.gov/gene/8676' target='_blank'>STX11</a>         |       8676 | ENSG00000135604 | AR        | NA  | syntaxin 11                                                                                       | PANEL_APP                                        | NA                                                                                                                                           |
| 386 | <a href='https://www.ncbi.nlm.nih.gov/gene/6813' target='_blank'>STXBP2</a>        |       6813 | ENSG00000076944 | AR        | NA  | syntaxin binding protein 2                                                                        | PANEL_APP                                        | NA                                                                                                                                           |
| 387 | <a href='https://www.ncbi.nlm.nih.gov/gene/51684' target='_blank'>SUFU</a>         |      51684 | ENSG00000107882 | AD/AR     | LoF | SUFU negative regulator of hedgehog signaling                                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Medulloblastoma; Hereditary Meningioma                                                                                                       |
| 388 | <a href='https://www.ncbi.nlm.nih.gov/gene/6850' target='_blank'>SYK</a>           |       6850 | ENSG00000165025 | NA        | NA  | spleen associated tyrosine kinase                                                                 | OTHER                                            | NA                                                                                                                                           |
| 389 | <a href='https://www.ncbi.nlm.nih.gov/gene/6862' target='_blank'>TBXT</a>          |       6862 | ENSG00000164458 | AD        | NA  | T-box transcription factor T                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 390 | <a href='https://www.ncbi.nlm.nih.gov/gene/6934' target='_blank'>TCF7L2</a>        |       6934 | ENSG00000148737 | NA        | NA  | transcription factor 7 like 2                                                                     | OTHER                                            | NA                                                                                                                                           |
| 391 | <a href='https://www.ncbi.nlm.nih.gov/gene/7012' target='_blank'>TERC</a>          |       7012 | ENSG00000277925 | AD        | NA  | telomerase RNA component                                                                          | PANEL_APP                                        | NA                                                                                                                                           |
| 392 | <a href='https://www.ncbi.nlm.nih.gov/gene/54386' target='_blank'>TERF2IP</a>      |      54386 | NA              | NA        | NA  | TERF2 interacting protein                                                                         | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 393 | <a href='https://www.ncbi.nlm.nih.gov/gene/7015' target='_blank'>TERT</a>          |       7015 | ENSG00000164362 | AD/AR     | LoF | telomerase reverse transcriptase                                                                  | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Autosomal dominant dyskeratosis congenita                                                                                                    |
| 394 | <a href='https://www.ncbi.nlm.nih.gov/gene/54790' target='_blank'>TET2</a>         |      54790 | ENSG00000168769 | NA        | NA  | tet methylcytosine dioxygenase 2                                                                  | OTHER                                            | NA                                                                                                                                           |
| 395 | <a href='https://www.ncbi.nlm.nih.gov/gene/7020' target='_blank'>TFAP2A</a>        |       7020 | ENSG00000137203 | AD        | NA  | transcription factor AP-2 alpha                                                                   | OTHER                                            | NA                                                                                                                                           |
| 396 | <a href='https://www.ncbi.nlm.nih.gov/gene/7030' target='_blank'>TFE3</a>          |       7030 | ENSG00000068323 | NA        | NA  | transcription factor binding to IGHM enhancer 3                                                   | OTHER                                            | NA                                                                                                                                           |
| 397 | <a href='https://www.ncbi.nlm.nih.gov/gene/7038' target='_blank'>TG</a>            |       7038 | ENSG00000042832 | AR        | NA  | thyroglobulin                                                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 398 | <a href='https://www.ncbi.nlm.nih.gov/gene/7046' target='_blank'>TGFBR1</a>        |       7046 | ENSG00000106799 | AD        | LoF | transforming growth factor beta receptor 1                                                        | ACMG_SF30,TCGA_PANCAN_2018                       | Multiple self-healing squamous epithelioma; Loeys-Dietz syndrome                                                                             |
| 399 | <a href='https://www.ncbi.nlm.nih.gov/gene/7048' target='_blank'>TGFBR2</a>        |       7048 | ENSG00000163513 | AR        | LoF | transforming growth factor beta receptor 2                                                        | ACMG_SF30,CGC_94                                 | Loeys-Dietz syndrome                                                                                                                         |
| 400 | <a href='https://www.ncbi.nlm.nih.gov/gene/26277' target='_blank'>TINF2</a>        |      26277 | ENSG00000092330 | AD        | NA  | TERF1 interacting nuclear factor 2                                                                | PANEL_APP                                        | NA                                                                                                                                           |
| 401 | <a href='https://www.ncbi.nlm.nih.gov/gene/11322' target='_blank'>TMC6</a>         |      11322 | ENSG00000141524 | AR        | NA  | transmembrane channel like 6                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 402 | <a href='https://www.ncbi.nlm.nih.gov/gene/147138' target='_blank'>TMC8</a>        |     147138 | ENSG00000167895 | AR        | NA  | transmembrane channel like 8                                                                      | PANEL_APP                                        | NA                                                                                                                                           |
| 403 | <a href='https://www.ncbi.nlm.nih.gov/gene/55654' target='_blank'>TMEM127</a>      |      55654 | ENSG00000135956 | AD/AR     | LoF | transmembrane protein 127                                                                         | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Pheochromocytoma; Hereditary Paraganglioma-Pheochromocytoma Syndromes                                                                        |
| 404 | <a href='https://www.ncbi.nlm.nih.gov/gene/7128' target='_blank'>TNFAIP3</a>       |       7128 | ENSG00000118503 | NA        | NA  | TNF alpha induced protein 3                                                                       | OTHER                                            | NA                                                                                                                                           |
| 405 | <a href='https://www.ncbi.nlm.nih.gov/gene/8792' target='_blank'>TNFRSF11A</a>     |       8792 | ENSG00000141655 | AD        | NA  | TNF receptor superfamily member 11a                                                               | PANEL_APP                                        | NA                                                                                                                                           |
| 406 | <a href='https://www.ncbi.nlm.nih.gov/gene/7157' target='_blank'>TP53</a>          |       7157 | ENSG00000141510 | AD/AR     | LoF | tumor protein p53                                                                                 | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | NA; Li-Fraumeni syndrome 1                                                                                                                   |
| 407 | <a href='https://www.ncbi.nlm.nih.gov/gene/8626' target='_blank'>TP63</a>          |       8626 | ENSG00000073282 | NA        | NA  | tumor protein p63                                                                                 | CGC_94                                           | NA                                                                                                                                           |
| 408 | <a href='https://www.ncbi.nlm.nih.gov/gene/8805' target='_blank'>TRIM24</a>        |       8805 | ENSG00000122779 | NA        | NA  | tripartite motif containing 24                                                                    | OTHER                                            | NA                                                                                                                                           |
| 409 | <a href='https://www.ncbi.nlm.nih.gov/gene/10155' target='_blank'>TRIM28</a>       |      10155 | ENSG00000130726 | AD        | NA  | tripartite motif containing 28                                                                    | PANEL_APP                                        | NA                                                                                                                                           |
| 410 | <a href='https://www.ncbi.nlm.nih.gov/gene/4591' target='_blank'>TRIM37</a>        |       4591 | ENSG00000108395 | AR        | LoF | tripartite motif containing 37                                                                    | PANEL_APP,TCGA_PANCAN_2018                       | NA                                                                                                                                           |
| 411 | <a href='https://www.ncbi.nlm.nih.gov/gene/9319' target='_blank'>TRIP13</a>        |       9319 | ENSG00000071539 | AR        | NA  | thyroid hormone receptor interactor 13                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 412 | <a href='https://www.ncbi.nlm.nih.gov/gene/7248' target='_blank'>TSC1</a>          |       7248 | ENSG00000165699 | AD/AR     | LoF | TSC complex subunit 1                                                                             | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Tuberous sclerosis syndrome; Tuberous sclerosis 1                                                                                            |
| 413 | <a href='https://www.ncbi.nlm.nih.gov/gene/7249' target='_blank'>TSC2</a>          |       7249 | ENSG00000103197 | AD/AR     | LoF | TSC complex subunit 2                                                                             | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Tuberous sclerosis syndrome; Tuberous sclerosis 2                                                                                            |
| 414 | <a href='https://www.ncbi.nlm.nih.gov/gene/7253' target='_blank'>TSHR</a>          |       7253 | ENSG00000165409 | AD        | NA  | thyroid stimulating hormone receptor                                                              | CGC_94,TCGA_PANCAN_2018                          | Hyperthyroidism, nonautoimmune                                                                                                               |
| 415 | <a href='https://www.ncbi.nlm.nih.gov/gene/90121' target='_blank'>TSR2</a>         |      90121 | ENSG00000158526 | NA        | NA  | TSR2 ribosome maturation factor                                                                   | PANEL_APP                                        | NA                                                                                                                                           |
| 416 | <a href='https://www.ncbi.nlm.nih.gov/gene/7297' target='_blank'>TYK2</a>          |       7297 | ENSG00000105397 | AR        | NA  | tyrosine kinase 2                                                                                 | OTHER                                            | NA                                                                                                                                           |
| 417 | <a href='https://www.ncbi.nlm.nih.gov/gene/29089' target='_blank'>UBE2T</a>        |      29089 | ENSG00000077152 | AR        | NA  | ubiquitin conjugating enzyme E2 T                                                                 | PANEL_APP                                        | NA                                                                                                                                           |
| 418 | <a href='https://www.ncbi.nlm.nih.gov/gene/201294' target='_blank'>UNC13D</a>      |     201294 | ENSG00000092929 | AD/AR     | NA  | unc-13 homolog D                                                                                  | PANEL_APP                                        | NA                                                                                                                                           |
| 419 | <a href='https://www.ncbi.nlm.nih.gov/gene/7389' target='_blank'>UROD</a>          |       7389 | ENSG00000126088 | AD/AR     | LoF | uroporphyrinogen decarboxylase                                                                    | TCGA_PANCAN_2018                                 | Familial porphyria cutanea tarda                                                                                                             |
| 420 | <a href='https://www.ncbi.nlm.nih.gov/gene/81839' target='_blank'>VANGL1</a>       |      81839 | ENSG00000173218 | NA        | NA  | VANGL planar cell polarity protein 1                                                              | OTHER                                            | NA                                                                                                                                           |
| 421 | <a href='https://www.ncbi.nlm.nih.gov/gene/7421' target='_blank'>VDR</a>           |       7421 | ENSG00000111424 | AD/AR     | NA  | vitamin D receptor                                                                                | PANEL_APP                                        | NA                                                                                                                                           |
| 422 | <a href='https://www.ncbi.nlm.nih.gov/gene/7428' target='_blank'>VHL</a>           |       7428 | ENSG00000134086 | AD/AR     | LoF | von Hippel-Lindau tumor suppressor                                                                | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Von Hippel-Lindau syndrome                                                                                                                   |
| 423 | <a href='https://www.ncbi.nlm.nih.gov/gene/100126299' target='_blank'>VTRNA2-1</a> |  100126299 | ENSG00000278815 | NA        | NA  | vault RNA 2-1                                                                                     | PANEL_APP                                        | NA                                                                                                                                           |
| 424 | <a href='https://www.ncbi.nlm.nih.gov/gene/7454' target='_blank'>WAS</a>           |       7454 | ENSG00000015285 | NA        | LoF | WASP actin nucleation promoting factor                                                            | CGC_94,PANEL_APP,TCGA_PANCAN_2018                | Thrombocytopenia 1                                                                                                                           |
| 425 | <a href='https://www.ncbi.nlm.nih.gov/gene/11197' target='_blank'>WIF1</a>         |      11197 | ENSG00000156076 | NA        | NA  | WNT inhibitory factor 1                                                                           | OTHER                                            | NA                                                                                                                                           |
| 426 | <a href='https://www.ncbi.nlm.nih.gov/gene/55135' target='_blank'>WRAP53</a>       |      55135 | ENSG00000141499 | AR        | NA  | WD repeat containing antisense to TP53                                                            | PANEL_APP                                        | NA                                                                                                                                           |
| 427 | <a href='https://www.ncbi.nlm.nih.gov/gene/7486' target='_blank'>WRN</a>           |       7486 | ENSG00000165392 | AR        | LoF | WRN RecQ like helicase                                                                            | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Werner syndrome                                                                                                                              |
| 428 | <a href='https://www.ncbi.nlm.nih.gov/gene/7490' target='_blank'>WT1</a>           |       7490 | ENSG00000184937 | AD/AR     | LoF | WT1 transcription factor                                                                          | ACMG_SF30,CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018 | Wilms tumor 1                                                                                                                                |
| 429 | <a href='https://www.ncbi.nlm.nih.gov/gene/7507' target='_blank'>XPA</a>           |       7507 | ENSG00000136936 | AR        | LoF | XPA, DNA damage recognition and repair factor                                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum group A                                                                                                                |
| 430 | <a href='https://www.ncbi.nlm.nih.gov/gene/7508' target='_blank'>XPC</a>           |       7508 | ENSG00000154767 | AR        | LoF | XPC complex subunit, DNA damage recognition and repair factor                                     | CGC_94,NCGC,PANEL_APP,TCGA_PANCAN_2018           | Xeroderma pigmentosum, group C                                                                                                               |
| 431 | <a href='https://www.ncbi.nlm.nih.gov/gene/7516' target='_blank'>XRCC2</a>         |       7516 | ENSG00000196584 | AR        | LoF | X-ray repair cross complementing 2                                                                | NCGC,PANEL_APP                                   | NA                                                                                                                                           |
| 432 | <a href='https://www.ncbi.nlm.nih.gov/gene/7517' target='_blank'>XRCC3</a>         |       7517 | ENSG00000126215 | AD        | NA  | X-ray repair cross complementing 3                                                                | OTHER                                            | NA                                                                                                                                           |
| 433 | <a href='https://www.ncbi.nlm.nih.gov/gene/7704' target='_blank'>ZBTB16</a>        |       7704 | ENSG00000109906 | NA        | NA  | zinc finger and BTB domain containing 16                                                          | OTHER                                            | NA                                                                                                                                           |
