
## Genomic biomarkers 

```{r prepare_germline_data}
#| echo: false
#| output: asis
#| eval: true

show_germline_filters <- list()
missing_germline_items <- list()
biomarker_present <- F
etype_set <- list()

for (etype in c("Predictive","Diagnostic",
                "Predisposing","Prognostic")) {
  show_germline_filters[[tolower(etype)]] <- F
  missing_germline_items[[tolower(etype)]] <- T
  
  if(NROW(cps_report[["content"]][["snv_indel"]]$callset$variant_display$bm) == 0){
    next
  }
  
  etype_set[[tolower(etype)]] <- 
    cps_report[["content"]][["snv_indel"]]$callset$variant_display$bm |>
    dplyr::filter(.data$BM_EVIDENCE_TYPE == etype)

  if (NROW(etype_set[[tolower(etype)]]) > 0) {
    etype_set[[tolower(etype)]] <- 
      etype_set[[tolower(etype)]] |>
      dplyr::arrange(.data$BM_EVIDENCE_LEVEL)
    show_germline_filters[[tolower(etype)]] <- T
    missing_germline_items[[tolower(etype)]] <- F
    biomarker_present <- T
  }
  if (NROW(etype_set[[tolower(etype)]]) > 2000){
    etype_set[[tolower(etype)]] <- 
      head(etype_set[[tolower(etype)]], 2000)
  }
}
```

- Germline DNA variants (__class 4/5__) in the targeted cancer predisposition genes that match with reported clinical evidence items from [CIViC](https://civicdb.org) and [CGI biomarker database](https://www.cancergenomeinterpreter.org/biomarkers) are listed. 

- Total number of _unique variants_ with clinical evidence associations: __N = `r cps_report[['content']][['snv_indel']]$v_stat_biomarker$n_var_eitems`__


```{r}
#| echo: false
#| output: asis
#| include: !expr isTRUE(NROW(cps_report$content$snv_indel$callset$variant_display$biomarker) > 0)

cat(paste0(
  "\n::: {.callout-important collapse='false'}\n## Note - biomarker resolution\n\n",
  "Germline biomarkers registered in CIViC are provided at different _resolutions_.",
  " The accuracy of a match between a germline variant ",
  "in the patient's sample and a clinical evidence item (biomarker) will vary accordingly, ",
  "as indicated by the styling of the <b>Alteration</b> column below:\n\n",
  "<div style='margin-bottom:6px;'>",
  "<span style='display:inline-block; width:9px; height:9px; border-radius:50%; ",
  "background-color:#37303A; margin-right:8px; vertical-align:middle;'></span>",
  "<span style='font-weight:600; color:#1a1a1a; vertical-align:middle;'>Bold text + filled circle</span>",
  " &mdash; high-resolution match (genomic position / amino acid / codon level)",
  "</div>",
  "<div style='margin-bottom:6px;'>",
  "<span style='display:inline-block; width:9px; height:9px; border-radius:50%; ",
  "background-color:transparent; border:2px solid #999999; margin-right:8px; vertical-align:middle;'></span>",
  "<span style='font-weight:400; color:#666666; vertical-align:middle;'>Normal text + hollow circle</span>",
  " &mdash; medium/low-resolution match (exon / gene level)",
  "</div>",
  "\n\n:::"
))
```

<br>


```{r biomarker_cpsr}
#| eval: true

rctbl_biomarker <- cpsr::prep_biomarker_tbl(rep = cps_report)
cpsr::render_actble_bm_table(
  rctbl_recs = rctbl_biomarker,
  color_palette = cpsr::color_palette
)

```

<br>

```{r pgx_cpsr}
#| child: 'quarto/cpsr_pgx.qmd'
#| eval: !expr isTRUE(as.logical(cps_report$settings$conf$variant_classification$pgx_findings))
```
