package:
  name: r-cpsr
  version: 2.1.1 # versioned by bump2version

source:
  path: ../../../

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    - r-base ==4.3.3
    - r-assertable
    - r-assertthat
    - r-bslib
    - r-crosstalk
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-glue
    - r-htmltools
    - r-openxlsx2
    - r-pcgrr
    - r-quarto
    - quarto
    - r-readr
    - r-rlang
    - r-shiny
    - r-stringr
    - r-stringi
    - r-tidyr
  run:
    - r-base ==4.3.3
    - r-assertable
    - r-assertthat
    - r-bslib
    - r-crosstalk
    - r-dplyr
    - r-dt
    - r-ggplot2
    - r-glue
    - r-htmltools
    - r-openxlsx2
    - r-pcgrr
    - r-quarto
    - quarto
    - r-readr
    - r-rlang
    - r-shiny
    - r-stringr
    - r-stringi
    - r-tidyr

test:
  commands:
    - $R -e "library('cpsr')"

about:
  home: https://github.com/sigven/cpsr
  license: MIT
  summary: Cancer Predisposition Sequencing Reporter
