package:
  name: r-cpsr
  version: 0.7.8 # versioned by bump2version

source:
  path: ../../../

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    - r-base ==4.1.1
    - r-pcgrr
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-log4r
    - r-magrittr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr
  run:
    - r-base ==4.1.1
    - r-pcgrr
    - r-assertthat
    - r-dplyr
    - r-ggplot2
    - r-log4r
    - r-magrittr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr

test:
  commands:
    - $R -e "library('cpsr')"

about:
  home: https://github.com/sigven/cpsr
  license: MIT
  summary: CPSR is a computational workflow that interprets germline variants identified from
           next-generation sequencing in the context of cancer predisposition. The workflow is
           integrated with the framework that underlies the Personal Cancer Genome Reporter
           (PCGR) (https://github.com/sigven/pcgr), utilizing the Docker environment for
           encapsulation of code and software dependencies. While PCGR is intended for reporting
           and analysis of somatic variants detected in a tumor, CPSR is intended for reporting
           and ranking of germline variants in protein-coding genes that are implicated in cancer
           predisposition and inherited cancer syndromes.
