context:
  name: r-cpsr
  version: 2.2.5.9008 # bump

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: generic
  script: R CMD INSTALL --build .

requirements:
  host:
    - conda-forge::r-base >=4.3,<4.6
    - conda-forge::r-assertable
    - conda-forge::r-assertthat
    - conda-forge::r-bslib
    - conda-forge::r-crosstalk
    - conda-forge::r-dplyr
    - conda-forge::r-dt
    - conda-forge::r-ggplot2
    - conda-forge::r-glue
    - conda-forge::r-htmltools
    - conda-forge::r-openxlsx2
    - r-pcgrr
    - conda-forge::r-quarto
    - conda-forge::quarto
    - conda-forge::r-reactable
    - conda-forge::r-readr
    - conda-forge::r-rlang
    - conda-forge::r-shiny
    - conda-forge::r-stringr
    - conda-forge::r-stringi
    - conda-forge::r-tidyr
  run:
    - conda-forge::r-base >=4.3,<4.6
    - conda-forge::r-assertable
    - conda-forge::r-assertthat
    - conda-forge::r-bslib
    - conda-forge::r-crosstalk
    - conda-forge::r-dplyr
    - conda-forge::r-dt
    - conda-forge::r-ggplot2
    - conda-forge::r-glue
    - conda-forge::r-htmltools
    - conda-forge::r-openxlsx2
    - r-pcgrr
    - conda-forge::r-quarto
    - conda-forge::quarto
    - conda-forge::r-reactable
    - conda-forge::r-readr
    - conda-forge::r-rlang
    - conda-forge::r-shiny
    - conda-forge::r-stringr
    - conda-forge::r-stringi
    - conda-forge::r-tidyr

tests:
  - r:
      libraries:
        - cpsr
about:
  homepage: https://sigven.github.io/cpsr
  summary: Cancer Predisposition Sequencing Reporter
  license: MIT
  license_file: LICENSE
  repository: https://github.com/sigven/cpsr
  documentation: https://sigven.github.io/cpsr

extra:
  recipe-maintainers:
    - pdiakumis

