{% set name = 'cpsr' %}
{% set version = os.environ.get('TRAVIS_TAG', '').replace('v.', '').replace('v', '') or 'dev' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0

requirements:
  run:
    - pcgr >=v0.8.1.1

test:
  commands:
    - cpsr.py --version

about:
  home: https://github.com/sigven/cpsr
  license: MIT
  summary: Cancer Predisposition Sequencing Reporter (CPSR) - prioritization of germline variants in cancer

