name: deploy

on:
  push:
    branches:
      - main
      - dev
env:
  conda_token: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  conda_recipe: conda/recipe
  conda_env_yaml: conda/env/yaml
  conda_org: pcgr
  VERSION: '2.2.5.9004' # versioned by bump2version
jobs:
  build_conda_pkg:
    # When merging to one of the branches above and the commit message matches
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v6
      - name: Set branch env vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "DEV_CONDA_CHANNEL=--channel ${{ env.conda_org }}/label/dev" >> $GITHUB_ENV
            echo "DEV_UPLOAD_LABEL=--channel dev" >> $GITHUB_ENV
          else
            echo "DEV_CONDA_CHANNEL=" >> $GITHUB_ENV
            echo "DEV_UPLOAD_LABEL=" >> $GITHUB_ENV
          fi
      - name: 👾 Miniforge setup
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: ${{ env.conda_env_yaml }}/condabuild.yaml
          activate-environment: condabuild_env
          miniforge-version: latest
      - name: 🐍🔧 Conda pkg build
        run: |
          rattler-build build \
            --recipe-dir ${{ env.conda_recipe }}/cpsr \
            ${{ env.DEV_CONDA_CHANNEL }} \
            --channel ${{ env.conda_org }} \
            --channel conda-forge \
            --channel bioconda \
            --output-dir ${RUNNER_TEMP}/out_cpsr
      - name: 🐍🪁 Conda pkg upload
        run: |
          pkg_path=$(find ${RUNNER_TEMP}/out_cpsr -type f -name "*.conda")
          rattler-build upload anaconda \
            --owner ${{ env.conda_org }} \
            --api-key ${{ env.conda_token }} \
            ${{ env.DEV_UPLOAD_LABEL }} \
            ${pkg_path}
      - name: 🔖 Tag creation
        uses: actions/github-script@v8
        with:
          script: |
            const the_tag_name = 'refs/tags/v' + process.env.VERSION
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: the_tag_name,
              sha: context.sha
            })

  publish_website:
    needs: build_conda_pkg
    name: Publish pkgdown website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: 🚚 Checkout tag
        uses: actions/checkout@v6
        with:
          ref: v${{ env.VERSION }}
      - name: Set pkgdown channels
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "PKGDOWN_CHANNELS=${{ env.conda_org }}/label/dev,pcgr,conda-forge,bioconda" >> $GITHUB_ENV
          else
            echo "PKGDOWN_CHANNELS=pcgr,conda-forge,bioconda" >> $GITHUB_ENV
          fi
      - name: 👾 Miniforge setup (pkgdown)
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: ${{ env.conda_env_yaml }}/pkgdown.yaml
          activate-environment: pkgdown_env
          miniforge-version: latest
          #channels: ${{ env.PKGDOWN_CHANNELS }}
          channel-priority: flexible
      - name: 🌐 Website publish
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          printf "cpsr version:\n"
          Rscript -e "packageVersion('cpsr')"
          Rscript -e "pkgdown::deploy_to_branch(pkg = '.', commit_message = 'Built CPSR website: https://sigven.github.io/cpsr/', branch = 'gh-pages', new_process = FALSE)"
