name: mambabuild

on:
  push:
    branches:
      - master
      - bundle_update_2023
env:
  atoken: ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
  recipe_path: conda/recipe
  env_yml_path: conda/env/yml
  VERSION: '1.0.1.9003' # versioned by bump2version
jobs:
  build_conda_pkgs:
    # When merging to one of the branches above and the commit message matches
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        r_version: ["4.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Micromamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ env.env_yml_path }}/condabuild_env.yml
      - name: Build + upload cpsr conda pkg
        run: |
          conda mambabuild ${recipe_path}/cpsr --R=${{ matrix.r_version }} -c pcgr -c conda-forge -c bioconda --token ${atoken}

  pkgdown_site:
    name: Deploy pkgdown website
    runs-on: ubuntu-latest
    needs: build_conda_pkgs
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Micromamba setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{ env.env_yml_path }}/pkgdown.yml
      - name: Publish pkgdown website
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            micromamba activate pkgdown
            printf "cpsr version:\n"
            Rscript -e "packageVersion('cpsr')"
            Rscript -e "pkgdown::deploy_to_branch(pkg = '.', commit_message = 'Built site for CPSR - see https://sigven.github.io/cpsr/'), branch = 'gh-pages', new_process = FALSE)"

      - name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            const the_tag_name = 'refs/tags/v' + process.env.VERSION
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: the_tag_name,
              sha: context.sha
            })
